Repository oasisprotocol/oasis-core, pull requests merged in 2019-11, with the labels that each got.

#2325 go: Update tendermint to 0.32.7
  go/go.mod
  go/go.sum
Labels: c:build, c:security

#2320 go/registry: Add stricter node registration checks
  go/common/crypto/signature/signature.go
  go/registry/api/api.go
  go/registry/tests/tester.go
  go/roothash/tests/tester.go
  go/scheduler/tests/tester.go
  go/storage/client/tests/tests.go
Labels: c:coordination, c:security

#2326 go/tendermint/abci: Enforce a maximum transaction size limit
  go/common/consensus/consensus.go
  go/oasis-node/cmd/genesis/genesis.go
  go/tendermint/abci/mux.go
Labels: c:backend-tendermint, c:security

#2288 Distribute staking rewards
  go/scheduler/api/api.go
  go/staking/api/api.go
  go/staking/api/rewards.go
  go/tendermint/apps/scheduler/scheduler.go
  go/tendermint/apps/staking/genesis.go
  go/tendermint/apps/staking/staking.go
  go/tendermint/apps/staking/state/state.go
  go/tendermint/apps/staking/state/state_test.go
Labels: c:backend-tendermint, c:breaking

#2328 Generalize ConsensusInfo's addresses
  go/common/consensus/consensus.go
  go/common/node/address.go
  go/common/node/address_test.go
  go/common/node/node.go
  go/grpc/common/common.proto
  go/oasis-node/cmd/registry/node/node.go
  go/oasis-test-runner/oasis/validator.go
  go/registry/api/api.go
  go/tendermint/api/api.go
  go/tendermint/tendermint.go
Labels: c:breaking-cfg, c:common

#2335 go/common/crypto/signature: Move `UnsafeBytes`
  go/common/crypto/signature/signer.go
  go/oasis-test-runner/oasis/seed.go
  go/tendermint/crypto/signature.go
  go/tendermint/crypto/signature_test.go
  go/tendermint/seed.go
  go/tendermint/tendermint.go
Labels: c:backend-tendermint, c:breaking, c:common

#2342 go/tendermint: Use our domain-separation signature scheme
  go/common/crypto/signature/signer.go
  go/common/crypto/signature/signers/file/file_signer.go
  go/common/crypto/signature/signers/memory/memory_signer.go
  go/go.mod
  go/go.sum
  go/oasis-test-runner/oasis/seed.go
  go/oasis-test-runner/oasis/validator.go
  go/tendermint/crypto/priv_val.go
  go/tendermint/crypto/signature.go
  go/tendermint/seed.go
  go/tendermint/tendermint.go
Labels: c:backend-tendermint, c:breaking, c:security

#2343 tests: Make E2E test coverage computation optional
  .buildkite/pipeline.yml
  .buildkite/scripts/test_e2e.sh
Labels: c:testing

#2348 go/tendermint/apps/registry: Limit node registrations by stake
  go/tendermint/apps/registry/registry.go
  go/tendermint/apps/registry/state/state.go
  go/tendermint/apps/staking/state/cache.go
Labels: c:backend-tendermint, c:coordination, c:security, c:staking

#2345 go/oasis-node/cmd/registry/node: Make consensus address' ID@ optional
  go/oasis-node/cmd/registry/node/node.go
  go/oasis-test-runner/oasis/validator.go
Labels: c:coordination

#2361 go: Bump the ed25519 and tendermint dependencies
  go/go.mod
  go/go.sum
Labels: c:bug

#2357 go/tendermint/apps/scheduler: Change the election behavior
  go/oasis-node/cmd/genesis/genesis.go
  go/scheduler/api/api.go
  go/tendermint/apps/scheduler/genesis.go
  go/tendermint/apps/scheduler/scheduler.go
  go/tendermint/apps/staking/state/cache.go
  go/tendermint/tests/genesis_testnode.go
Labels: c:backend-tendermint, c:breaking, c:coordination, c:staking

#2336 Add consensus gas fees
  go/common/consensus/gas/gas.go
  go/common/pubsub/pubsub.go
  go/common/quantity/quantity.go
  go/common/quantity/quantity_test.go
  go/common/version/version.go
  go/grpc/staking/staking.proto
  go/oasis-node/cmd/genesis/genesis.go
  go/oasis-node/cmd/stake/stake.go
  go/oasis-node/node_test.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/controller.go
  go/oasis-test-runner/oasis/fixture.go
  go/oasis-test-runner/oasis/validator.go
  go/oasis-test-runner/scenario/e2e/gas_fees.go
  go/oasis-test-runner/scenario/e2e/roothash_messages.go
  go/oasis-test-runner/test-runner.go
  go/roothash/api/block/header_test.go
  go/roothash/api/block/message.go
  go/roothash/tests/tester.go
  go/scheduler/api/api.go
  go/staking/api/api.go
  go/staking/api/api_test.go
  go/staking/api/rewards.go
  go/staking/api/slashing.go
  go/staking/client/client.go
  go/staking/grpc.go
  go/staking/tendermint/tendermint.go
  go/staking/tests/debug_stake.go
  go/staking/tests/tester.go
  go/tendermint/abci/context.go
  go/tendermint/abci/gas.go
  go/tendermint/abci/mux.go
  go/tendermint/apps/registry/registry.go
  go/tendermint/apps/staking/fees.go
  go/tendermint/apps/staking/genesis.go
  go/tendermint/apps/staking/query.go
  go/tendermint/apps/staking/staking.go
  go/tendermint/apps/staking/state/cache.go
  go/tendermint/apps/staking/state/gas.go
  go/tendermint/apps/staking/state/state.go
  go/tendermint/apps/staking/state/state_test.go
  go/tendermint/apps/staking/transactions.go
  go/tendermint/tendermint.go
  tests/fixture-data/gas-fees/staking-genesis.json
  tests/fixture-data/roothash-messages/staking-genesis.json
  tests/identities/byzantine.pem
  tests/identities/worker-1.pem
  tests/identities/worker-2.pem
  tests/identities/worker-3.pem
  tests/keymanager/internal-keys.cbor
  tests/keymanager/km-key.pem
  tests/keymanager/km.pem
Labels: c:breaking

#2370 go/tendermint/apps/scheduler: Change validator elections again
  go/oasis-node/cmd/genesis/genesis.go
  go/oasis-test-runner/oasis/oasis.go
  go/scheduler/api/api.go
  go/tendermint/apps/scheduler/genesis.go
  go/tendermint/apps/scheduler/scheduler.go
  go/tendermint/tests/genesis_testnode.go
Labels: c:breaking, c:breaking-cfg, c:coordination, c:staking

#2371 go/staking: Slash by fixed amount
  go/consensus/tendermint/apps/staking/slashing.go
  go/consensus/tendermint/apps/staking/state/state.go
  go/consensus/tendermint/apps/staking/state/state_test.go
  go/staking/api/slashing.go
  go/staking/tests/debug_stake.go
Labels: c:staking

#2372 go/consensus/tendermint/apps/scheduler: Change the validator incentives
  go/consensus/tendermint/apps/scheduler/scheduler.go
Labels: c:staking

#2375 Enable domain separation by ChainID for specific contexts
  go/common/crypto/signature/signer.go
  go/common/crypto/signature/signer_test.go
  go/consensus/tendermint/apps/roothash/genesis.go
  go/consensus/tendermint/tests/genesis_testnode.go
  go/genesis/file/file.go
  go/genesis/tests/tests.go
  go/oasis-node/cmd/debug/byzantine/tendermint.go
  go/oasis-node/cmd/node/node.go
  go/oasis-node/cmd/stake/account.go
  go/oasis-test-runner/oasis/oasis.go
  go/oasis-test-runner/scenario/e2e/halt_restore.go
  go/oasis-test-runner/scenario/e2e/stake_cli.go
  go/roothash/api/api.go
  go/roothash/api/block/block.go
  go/roothash/api/commitment/compute.go
  go/roothash/api/commitment/merge.go
  go/roothash/api/commitment/pool_test.go
  go/roothash/api/commitment/txnscheduler.go
  go/staking/api/api.go
  go/staking/tests/tendermint.go
  go/storage/api/api.go
  go/storage/mkvs/urkel/interop/cmd/protocol_server.go
  go/storage/tests/tester.go
Labels: c:breaking, c:breaking-cfg

#2300 Initial sentry node support
  go/.gitignore
  go/consensus/tendermint/api/api.go
  go/consensus/tendermint/tendermint.go
  go/grpc/build_protos.go
  go/grpc/sentry/sentry.proto
  go/oasis-node/cmd/node/node.go
  go/oasis-node/cmd/registry/node/node.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/fixture.go
  go/oasis-test-runner/oasis/log.go
  go/oasis-test-runner/oasis/oasis.go
  go/oasis-test-runner/oasis/sentry.go
  go/oasis-test-runner/oasis/validator.go
  go/oasis-test-runner/scenario/e2e/basic.go
  go/oasis-test-runner/scenario/e2e/sentry.go
  go/oasis-test-runner/test-runner.go
  go/sentry/api/api.go
  go/sentry/client/client.go
  go/sentry/grpc.go
  go/sentry/sentry.go
  go/worker/common/config.go
  go/worker/registration/worker.go
  go/worker/sentry/worker.go
Labels: c:breaking-cfg

#2384 go/registry/api: Allow deployments without a KM operator
  go/consensus/tendermint/apps/registry/genesis.go
  go/oasis-node/cmd/genesis/genesis.go
  go/registry/api/api.go
Labels: c:bug, c:coordination

#2380 go/common/crypto/signature: Fail when unmarshaling nil keys
  go/common/crypto/signature/signature.go
  go/common/node/node_test.go
  go/common/version/version.go
  go/registry/api/api.go
  go/registry/tests/tester.go
Labels: c:breaking

#2388 go/consensus/tendermint: Change private_peer config to private_peer_id
  go/consensus/tendermint/tendermint.go
  go/oasis-test-runner/oasis/args.go
Labels: c:backend-tendermint, c:breaking-cfg

#2391 scheduler: Bugfix and additional query
  go/consensus/tendermint/apps/scheduler/genesis.go
  go/consensus/tendermint/apps/scheduler/query.go
  go/consensus/tendermint/scheduler/scheduler.go
  go/oasis-node/node_test.go
  go/scheduler/api/api.go
Labels: c:bug, c:coordination

#2394 oasis-node: Deprecate `grpc.debug.port`
  go/consensus/tendermint/apps/roothash/roothash.go
  go/oasis-node/cmd/common/grpc/grpc.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/validator.go
  runtime/src/transaction/dispatcher.rs
  runtime/src/transaction/types.rs
Labels: c:security

#2337 registry: add runtime-specific RoundTimeout and committee sizes
  go/common/node/node.go
  go/common/version/version.go
  go/consensus/tendermint/apps/roothash/genesis.go
  go/consensus/tendermint/apps/roothash/query.go
  go/consensus/tendermint/apps/roothash/roothash.go
  go/consensus/tendermint/apps/roothash/state/state.go
  go/consensus/tendermint/apps/scheduler/scheduler.go
  go/consensus/tendermint/roothash/roothash.go
  go/consensus/tendermint/tests/genesis_testnode.go
  go/grpc/registry/runtime.proto
  go/oasis-net-runner/fixtures/default.go
  go/oasis-node/cmd/genesis/genesis.go
  go/oasis-node/cmd/registry/runtime/runtime.go
  go/oasis-node/node_test.go
  go/oasis-test-runner/oasis/fixture.go
  go/oasis-test-runner/oasis/oasis.go
  go/oasis-test-runner/oasis/runtime.go
  go/oasis-test-runner/scenario/e2e/basic.go
  go/oasis-test-runner/scenario/e2e/roothash_messages.go
  go/registry/api/api.go
  go/registry/api/runtime.go
  go/registry/api/runtime_test.go
  go/registry/tests/tester.go
  go/roothash/api/api.go
  go/roothash/api/commitment/pool.go
  go/roothash/tests/tester.go
  go/scheduler/api/api.go
  go/scheduler/tests/tester.go
  go/worker/common/committee/group.go
  go/worker/merge/committee/node.go
  go/worker/txnscheduler/algorithm/api/api.go
  go/worker/txnscheduler/algorithm/batching/batching.go
  go/worker/txnscheduler/committee/node.go
  go/worker/txnscheduler/init.go
  go/worker/txnscheduler/worker.go
Labels: c:breaking, c:breaking-cfg

#2398 misc: Go back to serializing certain things as CBOR arrays
  go/common/version/version.go
  go/go.mod
  go/go.sum
  go/runtime/transaction/transaction.go
  go/runtime/transaction/transaction_test.go
  go/storage/mkvs/urkel/db/badger/badger.go
  go/storage/mkvs/urkel/db/leveldb/leveldb.go
  go/storage/mkvs/urkel/writelog/writelog.go
  runtime/src/common/version.rs
  runtime/src/storage/mkvs/mod.rs
  runtime/src/transaction/tree.rs
Labels: c:breaking

#2396 ci: put coverage aside
  .buildkite/pipeline.yml
  docker/development/Dockerfile
Labels: c:build, c:testing

#2401 ci: clean up remaining tool installation
  .buildkite/pipeline.yml
Labels: c:build

#2353 Staking commission
  go/common/version/version.go
  go/consensus/tendermint/apps/staking/api.go
  go/consensus/tendermint/apps/staking/staking.go
  go/consensus/tendermint/apps/staking/state/state.go
  go/consensus/tendermint/apps/staking/state/state_test.go
  go/consensus/tendermint/apps/staking/transactions.go
  go/consensus/tendermint/staking/staking.go
  go/genesis/api/api.go
  go/grpc/staking/staking.proto
  go/oasis-node/cmd/stake/account.go
  go/oasis-test-runner/scenario/e2e/stake_cli.go
  go/staking/api/api.go
  go/staking/api/commission.go
  go/staking/api/commission_test.go
  go/staking/api/rewards.go
  go/staking/client/client.go
  go/staking/grpc.go
  tests/fixture-data/stake-cli/staking-genesis.json
Labels: c:backend-tendermint, c:breaking, c:staking

#2412 oasis-node: Feature-gate all unsafe/debug/test flags
  go/beacon/api/api.go
  go/common/crash/crash.go
  go/common/crash/crash_test.go
  go/common/grpc/grpc.go
  go/consensus/tendermint/tendermint.go
  go/epochtime/api/api.go
  go/ias/ias.go
  go/keymanager/client/client.go
  go/oasis-node/cmd/common/common.go
  go/oasis-node/cmd/common/flags/flags.go
  go/oasis-node/cmd/debug/byzantine/byzantine.go
  go/oasis-node/cmd/debug/storage/storage.go
  go/oasis-node/cmd/genesis/genesis.go
  go/oasis-node/cmd/ias/proxy.go
  go/oasis-node/cmd/keymanager/keymanager.go
  go/oasis-node/cmd/node/node.go
  go/oasis-node/node_test.go
  go/oasis-test-runner/cmd/root.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/byzantine.go
  go/oasis-test-runner/oasis/client.go
  go/oasis-test-runner/oasis/compute.go
  go/oasis-test-runner/oasis/entity.go
  go/oasis-test-runner/oasis/ias.go
  go/oasis-test-runner/oasis/keymanager.go
  go/oasis-test-runner/oasis/seed.go
  go/oasis-test-runner/oasis/sentry.go
  go/oasis-test-runner/oasis/storage.go
  go/oasis-test-runner/oasis/validator.go
  go/oasis-test-runner/scenario/e2e/stake_cli.go
  go/oasis-test-runner/scenario/e2e/storage_sync.go
  go/registry/api/api.go
  go/scheduler/api/api.go
  go/storage/client/init.go
  go/storage/init.go
Labels: c:breaking-cfg

#2424 registry validation consistency
  go/common/node/node.go
  go/common/version/version.go
  go/oasis-node/cmd/debug/byzantine/byzantine.go
  go/oasis-node/cmd/debug/byzantine/registry.go
  go/oasis-node/cmd/node/node.go
  go/registry/api/api.go
  go/registry/tests/tester.go
  go/worker/common/p2p/p2p.go
  go/worker/compute/worker.go
  go/worker/keymanager/init.go
  go/worker/keymanager/worker.go
  go/worker/merge/worker.go
  go/worker/registration/worker.go
  go/worker/storage/worker.go
  go/worker/txnscheduler/worker.go
Labels: c:breaking

#2386 Registry gas fees
  go/consensus/tendermint/abci/gas.go
  go/consensus/tendermint/abci/gas_test.go
  go/consensus/tendermint/apps/registry/registry.go
  go/consensus/tendermint/apps/registry/transactions.go
  go/consensus/tendermint/apps/staking/transactions.go
  go/keymanager/client/client.go
  go/oasis-net-runner/fixtures/default.go
  go/oasis-node/cmd/debug/byzantine/registry.go
  go/oasis-test-runner/oasis/byzantine.go
  go/oasis-test-runner/oasis/compute.go
  go/oasis-test-runner/oasis/entity.go
  go/oasis-test-runner/oasis/keymanager.go
  go/oasis-test-runner/oasis/oasis.go
  go/oasis-test-runner/oasis/storage.go
  go/oasis-test-runner/oasis/validator.go
  go/oasis-test-runner/scenario/e2e/basic.go
  go/oasis-test-runner/scenario/e2e/gas_fees.go
  go/oasis-test-runner/scenario/e2e/roothash_messages.go
  go/registry/api/api.go
  go/registry/tests/tester.go
  go/staking/api/api.go
  go/worker/registration/worker.go
Labels: c:breaking

#2430 go: Bump tendermint to 0.32.8 + our patches
  go/common/crypto/mrae/api/api.go
  go/consensus/tendermint/api/api.go
  go/consensus/tendermint/tendermint.go
  go/go.mod
  go/go.sum
Labels: c:breaking

#2404 abci: move calling InitChain on apps from BeginBlock to mux InitChain
  go/common/version/version.go
  go/consensus/tendermint/abci/mux.go
  go/consensus/tendermint/apps/beacon/query.go
  go/consensus/tendermint/apps/epochtime_mock/query.go
  go/consensus/tendermint/apps/keymanager/query.go
  go/consensus/tendermint/apps/registry/query.go
  go/consensus/tendermint/apps/roothash/query.go
  go/consensus/tendermint/apps/scheduler/query.go
  go/consensus/tendermint/apps/staking/query.go
  go/consensus/tendermint/tendermint.go
  go/worker/common/worker.go
Labels: c:breaking

#2437 Use genesis document hash instead of ChainID for chain domain separation
  go/common/crypto/signature/signer.go
  go/common/crypto/signature/signer_test.go
  go/consensus/tendermint/seed.go
  go/consensus/tendermint/tendermint.go
  go/genesis/api/api.go
  go/genesis/api/api_test.go
  go/genesis/tests/tests.go
  go/oasis-node/cmd/common/consensus/consensus.go
  go/oasis-node/cmd/debug/byzantine/tendermint.go
  go/oasis-node/cmd/node/node.go
  go/oasis-test-runner/oasis/oasis.go
  go/staking/gen_vectors/main.go
Labels: c:breaking
