Repository oasisprotocol/oasis-core, pull requests merged in 2020-12, with the labels that each got.

#3538 Fix storage sync after non-zero genesis
  .changelog/3538.bugfix.md
  .changelog/3538.internal.md
  go/oasis-node/cmd/registry/runtime/runtime.go
  go/oasis-test-runner/oasis/cli/cli.go
  go/oasis-test-runner/oasis/oasis.go
  go/oasis-test-runner/scenario/e2e/e2e.go
  go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
  go/storage/mkvs/checkpoint/checkpointer.go
  go/storage/mkvs/checkpoint/checkpointer_test.go
  go/worker/storage/committee/node.go
Labels: c:runtime, c:storage

#3540 [BACKPORT/20.12.x] Fix storage sync after non-zero genesis
  .changelog/3538.bugfix.md
  .changelog/3538.internal.md
  go/oasis-node/cmd/registry/runtime/runtime.go
  go/oasis-test-runner/oasis/cli/cli.go
  go/oasis-test-runner/oasis/oasis.go
  go/oasis-test-runner/scenario/e2e/e2e.go
  go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
  go/storage/mkvs/checkpoint/checkpointer.go
  go/storage/mkvs/checkpoint/checkpointer_test.go
  go/worker/storage/committee/node.go
Labels: c:backport

#3542 docs: Fix link to Tendermint Metrics documentation
  .changelog/3542.trivial.md
  docs/oasis-node/metrics.md
  docs/oasis-node/metrics.md.tpl
Labels: c:docs

#3545 go/roothash/api/commitment: Return proposer commit in DR
  .changelog/3545.bugfix.md
  go/consensus/tendermint/apps/roothash/roothash.go
  go/roothash/api/commitment/pool.go
  go/roothash/api/commitment/pool_test.go
Labels: c:bug

#3547 [BACKPORT/20.12.x] go/common/version: Add ConvertGoModulesVersion() function
  .changelog/3546.feature.md
  go/common/version/version.go
  go/common/version/version_test.go
Labels: c:backport

#3546 go/common/version: Add ConvertGoModulesVersion() function
  .changelog/3546.feature.md
  go/common/version/version.go
  go/common/version/version_test.go
Labels: c:common, golang

#3552 [BACKPORT/20.12.x] Fix registration transaction signing with Ledger signer plugin
  .changelog/3505.bugfix.md
  .changelog/3506.internal.md
  go/oasis-node/cmd/common/consensus/consensus.go
  go/oasis-node/cmd/keymanager/keymanager.go
  go/oasis-node/cmd/registry/entity/entity.go
  go/oasis-node/cmd/registry/runtime/runtime.go
  go/oasis-node/cmd/stake/account.go
Labels: c:backport

#3506 Fix registration transaction signing with Ledger signer plugin
  .changelog/3505.bugfix.md
  .changelog/3506.internal.md
  go/oasis-node/cmd/common/consensus/consensus.go
  go/oasis-node/cmd/keymanager/keymanager.go
  go/oasis-node/cmd/registry/entity/entity.go
  go/oasis-node/cmd/registry/runtime/runtime.go
  go/oasis-node/cmd/stake/account.go
Labels: c:bug, c:cli, c:registry

#3554 changelog: Update fragments with mini fixes from 20.12.3 release
  .changelog/3481.bugfix.md
  .changelog/3497.bugfix.md
  .changelog/3534.bugfix.md
  .changelog/3554.trivial.md
Labels: c:docs

#3556 go/oasis-node/cmd/common: Add LoadEntitySigner() helper
  .changelog/3556.internal.md
  go/oasis-node/cmd/common/common.go
  go/oasis-node/cmd/common/consensus/consensus.go
  go/oasis-node/cmd/registry/entity/entity.go
  go/oasis-node/cmd/registry/node/node.go
  go/oasis-node/cmd/registry/runtime/runtime.go
Labels: c:cli

#3559 go/oasis-node/cmd: Add oasis-node stake account nonce CLI command
  .changelog/3559.feature.md
  go/oasis-node/cmd/stake/account.go
  go/oasis-test-runner/scenario/e2e/stake_cli.go
Labels: c:cli

#3568 go/oasis-node/txsource: Increase submission timeout
  .changelog/3568.internal.md
  go/oasis-node/cmd/debug/txsource/workload/workload.go
Labels: c:testing

#3569 go/runtime/scheduling: Consumer should pull from scheduler
  .changelog/3569.bugfix.md
  go/runtime/scheduling/api/api.go
  go/runtime/scheduling/simple/simple.go
  go/runtime/scheduling/simple/txpool/orderedmap/ordered_map.go
  go/runtime/scheduling/simple/txpool/tester.go
  go/runtime/scheduling/tests/tester.go
  go/worker/compute/executor/committee/node.go
Labels: c:bug, c:runtime/scheduler

#3570 go/oasis-node/cmd: Add oasis-node stake account validate_address cmd
  .changelog/3493.feature..md
  go/oasis-node/cmd/stake/account.go
  go/oasis-test-runner/scenario/e2e/stake_cli.go
Labels: c:cli, c:staking

#3589 go/oasis-node/cmd: Fix output of stake account validate_address cmd
  .changelog/3493.feature.md
  .changelog/3589.feature.md
  go/oasis-node/cmd/stake/account.go
Labels: c:cli, c:staking
