Repository oasisprotocol/oasis-core, pull requests merged in 2020-11, with the labels that each got.

#3458 go/common/crypto: Bump ed25519 version
  .changelog/3458.breaking.md
  go/common/crypto/signature/signature.go
  go/common/crypto/signature/signer_test.go
  go/common/crypto/signature/tests/blacklist_test.go
  go/genesis/genesis_test.go
  go/go.mod
  go/go.sum
  go/registry/tests/tester.go
Labels: c:breaking/consensus, c:common

#3461 [BACKPORT/20.12.x] go/common/crypto: Bump ed25519 version
  .changelog/3458.breaking.md
  .changelog/3460.bugfix.md
  Cargo.lock
  go/common/crypto/signature/signature.go
  go/common/crypto/signature/signer_test.go
  go/common/crypto/signature/tests/blacklist_test.go
  go/common/version/version.go
  go/genesis/genesis_test.go
  go/go.mod
  go/go.sum
  go/registry/tests/tester.go
  runtime-loader/Cargo.toml
Labels: c:backport

#3471 go/common/crypto: Bump ed25519 version
  .changelog/3471.trivial.md
  go/go.mod
  go/go.sum
Labels: c:breaking/consensus

#3472 [BACKPORT/20.12.x] go/common/crypto: Bump ed25519 version (again)
  .changelog/3471.trivial.md
  go/go.mod
  go/go.sum
Labels: c:backport

#3478 [BACKPORT/20.12.x] go/genesis: Fix epoch-based sanity checks
  .changelog/3477.bugfix.md
  go/consensus/tendermint/abci/mux.go
  go/consensus/tendermint/abci/state.go
  go/epochtime/api/api.go
  go/genesis/api/sanity_check.go
  go/genesis/genesis_test.go
Labels: c:backport

#3477 go/genesis: Fix epoch-based sanity checks
  .changelog/3477.breaking.md
  .changelog/3477.bugfix.md
  go/consensus/tendermint/abci/mux.go
  go/consensus/tendermint/abci/state.go
  go/epochtime/api/api.go
  go/genesis/api/sanity_check.go
  go/genesis/genesis_test.go
Labels: c:bug

#3492 Make: Improve project version handling
  .changelog/3492.internal.md
  Makefile
  common.mk
  docs/release-process.md
Labels: c:ops

#3497 go: Add missing size checks in UnmarshalBinary
  .changelog/3497.bugfix.md
  go/common/sgx/common.go
  go/common/sgx/ias/quote.go
  go/storage/mkvs/node/depth.go
Labels: c:bug, c:common

#3423 ADR 0006: Consensus Governance
  .changelog/3423.doc.md
  docs/adr/0006-consensus-governance.md
  docs/adr/index.md
Labels: c:docs/adr

#3499 runtime: Add mkvs::OverlayTree and use it in the dispatcher
  .changelog/3499.bugfix.1.md
  .changelog/3499.bugfix.2.md
  .changelog/3499.feature.1.md
  .changelog/3499.feature.2.md
  .changelog/3499.feature.3.md
  client/src/transaction/snapshot.rs
  go/storage/mkvs/iterator.go
  go/storage/mkvs/lookup.go
  go/storage/mkvs/overlay.go
  go/storage/mkvs/overlay_test.go
  go/storage/mkvs/syncer/proof.go
  go/storage/mkvs/syncer_test.go
  go/storage/mkvs/tree_test.go
  runtime/src/dispatcher.rs
  runtime/src/storage/context.rs
  runtime/src/storage/mkvs/mod.rs
  runtime/src/storage/mkvs/sync/test.rs
  runtime/src/storage/mkvs/tree/commit.rs
  runtime/src/storage/mkvs/tree/insert.rs
  runtime/src/storage/mkvs/tree/iterator.rs
  runtime/src/storage/mkvs/tree/lookup.rs
  runtime/src/storage/mkvs/tree/mkvs.rs
  runtime/src/storage/mkvs/tree/mod.rs
  runtime/src/storage/mkvs/tree/overlay.rs
  runtime/src/storage/mkvs/tree/remove.rs
  runtime/src/storage/mkvs/tree/tree.rs
  runtime/src/storage/mkvs/tree/tree_test.rs
  runtime/src/transaction/tree.rs
Labels: c:breaking/runtime

#3512 Bump Go to 1.15.5
  .changelog/3512.bugfix.md
  .github/workflows/release.yml
  docker/development/Dockerfile
  docs/setup/prerequisites.md
Labels: c:security

#3515 [BACKPORT/20.12.x] Bump Go to 1.15.5
  .changelog/3512.bugfix.md
  .github/workflows/release.yml
  docker/development/Dockerfile
  docs/setup/prerequisites.md
Labels: c:backport, c:security

#3522 github: Replace deprecated set-env command with environment file
  .changelog/3522.internal.md
  .github/workflows/release.yml
Labels: c:ops

#3523 [BACKPORT/20.12.x] Bump GitHub Actions' versions
  .changelog/3349.internal.md
  .changelog/3364.internal.md
  .changelog/3365.internal.md
  .changelog/3367.internal.md
  .changelog/3405.internal.md
  .github/workflows/ci-lint.yml
  .github/workflows/ci-reproducibility.yml
  .github/workflows/release.yml
Labels: c:backport, c:ops

#3534 go tendermint: status peers and validator only after started
  .changelog/3534.bugfix.md
  go/consensus/tendermint/full/full.go
Labels: c:bug

#3535 backport #3534 to 20.12.x
  .changelog/3534.bugfix.md
  go/consensus/tendermint/full/full.go
Labels: c:backport, c:bug
