Repository oasisprotocol/oasis-core, pull requests merged in 2021-08, with the labels that each got.

#4167 go/registry/gen_vectors: Stop generating transactions for v1 entities
  .changelog/4167.internal.md
  go/registry/gen_vectors/main.go
Labels: c:registry, c:testing

#4169 ci: bump longtests timeout
  .buildkite/longtests.pipeline.yml
  .changelog/4169.trivial.md
Labels: s:ready-ci

#4166 runtime/client: SubmitTx variant that returns metadata
  .changelog/4162.feature.md
  go/oasis-node/cmd/debug/txsource/workload/runtime.go
  go/runtime/client/api/api.go
  go/runtime/client/api/grpc.go
  go/runtime/client/client.go
  go/runtime/client/submitter.go
  go/runtime/client/tests/tester.go
  go/runtime/host/mock/mock.go
Labels: s:ready-ci

#4177 go/registry/api: Add its own body type to MethodDeregisterEntity
  .changelog/4177.feature.md
  .changelog/4177.internal.md
  go/registry/api/api.go
  go/registry/gen_vectors/main.go
Labels: c:registry, c:testing

#4179 go/oasis-test-runner: support for testing update handlers
  .changelog/4179.internal.md
  go/oasis-test-runner/scenario/e2e/e2e.go
  go/oasis-test-runner/scenario/e2e/upgrade.go
Labels: s:ready-ci

#4176 go: update gofumpt to 0.1.1
  .changelog/4176.internal.md
  docker/development/Dockerfile
  docs/setup/prerequisites.md
  go/.golangci.yml
  go/Makefile
  go/common/grpc/cbor.go
  go/common/grpc/errors_test.go
  go/common/grpc/testing/ping.go
  go/common/grpc/wrapper_test.go
  go/consensus/api/transaction/transaction_test.go
  go/consensus/tendermint/api/api.go
  go/keymanager/api/grpc.go
  go/oasis-node/cmd/common/metrics/net.go
  go/registry/api/runtime.go
  go/runtime/history/history_test.go
  go/runtime/history/prune.go
  go/runtime/host/host.go
  go/runtime/host/mock/mock.go
  go/runtime/host/protocol/connection.go
  go/runtime/host/protocol/types.go
  go/runtime/tagindexer/backend.go
  go/storage/mkvs/db/badger/migrate_test.go
  go/storage/mkvs/interop/fixtures/consensus_mock.go
  go/storage/mkvs/syncer/merge.go
  go/storage/mkvs/syncer/proof.go
  go/upgrade/migrations/dummy.go
Labels: s:ready-ci

#4181 [BACKPORT/21.2.x] go/oasis-test-runner: support for testing upgrade handlers
  .changelog/4179.internal.md
  go/oasis-test-runner/scenario/e2e/e2e.go
  go/oasis-test-runner/scenario/e2e/upgrade.go
Labels: c:backport

#4187 go/roothash: adds ConsensusParameters method
  .changelog/4187.feature.md
  go/consensus/tendermint/apps/roothash/query.go
  go/consensus/tendermint/roothash/roothash.go
  go/oasis-test-runner/oasis/controller.go
  go/roothash/api/api.go
  go/roothash/api/grpc.go
  go/roothash/tests/tester.go
  go/staking/api/api.go
Labels: s:ready-ci

#4188 [BACPORT/21.2.x] go/roothash: adds ConsensusParameters method
  .changelog/4187.feature.md
  go/consensus/tendermint/apps/roothash/query.go
  go/consensus/tendermint/roothash/roothash.go
  go/oasis-test-runner/oasis/controller.go
  go/roothash/api/api.go
  go/roothash/api/grpc.go
  go/roothash/tests/tester.go
  go/staking/api/api.go
Labels: c:backport, s:ready-ci

#4178 [BACKPORT/21.2.x] go/registry: Update test vectors and add its own body type to MethodDeregisterEntity
  .changelog/4167.internal.md
  .changelog/4177.feature.md
  .changelog/4177.internal.md
  go/registry/api/api.go
  go/registry/gen_vectors/main.go
Labels: c:backport

#4189 [BACKPORT/21.2.x] go: update gofumpt and golangci-lint
  .changelog/4176.internal.md
  .changelog/4190.internal.md
  docker/development/Dockerfile
  docs/setup/prerequisites.md
  go/.golangci.yml
  go/Makefile
  go/common/crash/crash.go
  go/common/grpc/cbor.go
  go/common/grpc/errors_test.go
  go/common/grpc/testing/ping.go
  go/common/grpc/wrapper_test.go
  go/consensus/api/transaction/transaction_test.go
  go/consensus/tendermint/api/api.go
  go/consensus/tendermint/apps/keymanager/keymanager.go
  go/consensus/tendermint/apps/roothash/transactions.go
  go/consensus/tendermint/apps/staking/state/state.go
  go/consensus/tendermint/apps/supplementarysanity/checks.go
  go/governance/api/api_test.go
  go/governance/api/proposal_test.go
  go/keymanager/api/grpc.go
  go/oasis-node/cmd/common/metrics/net.go
  go/oasis-node/cmd/debug/byzantine/scheduler.go
  go/oasis-node/cmd/debug/byzantine/storage_node.go
  go/oasis-node/cmd/debug/byzantine/tendermint.go
  go/oasis-node/cmd/debug/txsource/workload/parallel.go
  go/oasis-node/cmd/debug/txsource/workload/queries.go
  go/oasis-node/cmd/debug/txsource/workload/runtime.go
  go/oasis-node/cmd/node/node.go
  go/oasis-node/cmd/storage/storage.go
  go/oasis-node/node_test.go
  go/oasis-test-runner/scenario/e2e/runtime/client_expire.go
  go/oasis-test-runner/scenario/e2e/runtime/late_start.go
  go/registry/api/runtime.go
  go/runtime/history/history_test.go
  go/runtime/history/prune.go
  go/runtime/host/host.go
  go/runtime/host/mock/mock.go
  go/runtime/host/protocol/connection.go
  go/runtime/host/protocol/types.go
  go/runtime/tagindexer/backend.go
  go/scheduler/tests/tester.go
  go/sentry/api/api.go
  go/storage/mkvs/db/badger/migrate_test.go
  go/storage/mkvs/interop/cmd/protocol_server.go
  go/storage/mkvs/interop/fixtures/consensus_mock.go
  go/storage/mkvs/syncer/merge.go
  go/storage/mkvs/syncer/proof.go
  go/upgrade/migrations/consensus_max_allowances.go
  go/upgrade/migrations/dummy.go
  go/worker/common/p2p/dispatch.go
  go/worker/compute/executor/committee/state.go
  go/worker/storage/worker.go
Labels: c:backport

#4194 [BACKPORT/21.2.x] prevent startup when RLIMIT_NOFILE is too low
  .changelog/4192.feature.md
  go/oasis-node/cmd/common/common.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/byzantine.go
  go/oasis-test-runner/oasis/client.go
  go/oasis-test-runner/oasis/compute.go
  go/oasis-test-runner/oasis/ias.go
  go/oasis-test-runner/oasis/keymanager.go
  go/oasis-test-runner/oasis/seed.go
  go/oasis-test-runner/oasis/sentry.go
  go/oasis-test-runner/oasis/storage.go
  go/oasis-test-runner/oasis/validator.go
Labels: c:backport

#4216 go/runtime: Remove tag indexer
  .changelog/3888.breaking.md
  .changelog/3888.cfg.md
  go/go.mod
  go/go.sum
  go/oasis-node/cmd/debug/txsource/workload/queries.go
  go/oasis-node/node_test.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/client.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_message.go
  go/runtime/client/api/api.go
  go/runtime/client/api/grpc.go
  go/runtime/client/client.go
  go/runtime/client/tests/tester.go
  go/runtime/registry/config.go
  go/runtime/registry/registry.go
  go/runtime/tagindexer/backend.go
  go/runtime/tagindexer/backend_test.go
  go/runtime/tagindexer/bleve.go
  go/runtime/tagindexer/tagindexer.go
Labels: c:breaking/cfg, c:breaking

#4229 go/tests/e2e: validator-equivocation test scenario
  .changelog/4223.internal.md
  Makefile
  go/consensus/tendermint/tests/evidence.go
  go/oasis-test-runner/scenario/e2e/e2e.go
  go/oasis-test-runner/scenario/e2e/validator_equivocation.go
  go/staking/tests/tester.go
Labels: s:ready-ci
