Repository oasisprotocol/oasis-core, pull requests merged in 2021-07, with the labels that each got.

#4107 go/worker/compute: Replicate input batch locally
  .changelog/4107.bugfix.md
  go/storage/api/mux.go
  go/storage/api/mux_test.go
  go/worker/common/committee/group.go
  go/worker/compute/executor/committee/node.go
Labels: c:bug, c:runtime/compute, c:storage

#4108 [BACKPORT/21.2.x] go/worker/compute: Replicate input batch locally
  .changelog/4107.bugfix.md
  go/storage/api/mux.go
  go/storage/api/mux_test.go
  go/worker/common/committee/group.go
  go/worker/compute/executor/committee/node.go
Labels: c:backport

#4110 go/consensus/tendermint: Correctly propagate errors
  .changelog/4110.bugfix.md
  go/consensus/tendermint/apps/staking/proposing_rewards.go
  go/consensus/tendermint/apps/staking/staking.go
  go/consensus/tendermint/apps/staking/votes.go
Labels: c:bug, c:consensus/tendermint

#4112 [BACKPORT/21.2.x] go/consensus/tendermint: Correctly propagate errors
  .changelog/4110.bugfix.md
  go/consensus/tendermint/apps/staking/proposing_rewards.go
  go/consensus/tendermint/apps/staking/staking.go
  go/consensus/tendermint/apps/staking/votes.go
Labels: c:backport

#4118 [BACKPORT/21.2.x] go/runtime/host/sandbox: Add deadline to bwrap pipes
  .changelog/4111.bugfix.md
  go/runtime/host/sandbox/process/bwrap.go
Labels: c:backport

#4127 Bump BadgerDB to v3.2103.1
  .changelog/4127.internal.md
  go/go.mod
  go/go.sum
Labels: c:deps

#4130 bump tendermint to latest revision
  .changelog/4130.trivial.md
  Cargo.lock
  runtime/Cargo.toml
Labels: s:ready-ci

#4131 go/worker/executor: batch CheckTx transactions
  .changelog/2548.feature.md
  go/runtime/client/client.go
  go/runtime/client/tests/tester.go
  go/runtime/host/helpers.go
  go/runtime/scheduling/simple/orderedmap/ordered_map.go
  go/runtime/scheduling/simple/orderedmap/ordered_map_test.go
  go/worker/compute/executor/committee/batch.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/init.go
  go/worker/compute/executor/tests/tester.go
  go/worker/compute/executor/worker.go
Labels: s:ready-ci
