Repository oasisprotocol/oasis-core, pull requests merged in 2021-04, with the labels that each got.

#3831 [BACKPORT/21.0.x] Checkpoint abort fixes
  .changelog/3830.bugfix.md
  go/consensus/tendermint/abci/mux.go
  go/storage/mkvs/checkpoint/checkpoint.go
  go/storage/mkvs/checkpoint/checkpoint_test.go
  go/storage/mkvs/checkpoint/restorer.go
  go/storage/mkvs/db/badger/badger_test.go
  go/worker/storage/committee/checkpoint_sync.go
  go/worker/storage/committee/node.go
Labels: c:backport

#3845 go/consensus/api/transaction/testvector: Extend TestVector to suport the notion of a (statically) valid transaction
  .changelog/3845.breaking.1.md
  .changelog/3845.breaking.2.md
  .changelog/3845.breaking.3.md
  .changelog/3845.feature.2.md
  .changelog/3845.feature.3.md
  .changelog/3845.internal.md
  docs/consensus/test-vectors.md
  go/common/entity/entity.go
  go/common/version/version.go
  go/common/version/version_test.go
  go/consensus/api/transaction/testvectors/testvectors.go
  go/consensus/tendermint/apps/governance/governance_test.go
  go/consensus/tendermint/apps/registry/transactions_test.go
  go/genesis/genesis_test.go
  go/governance/gen_vectors/main.go
  go/oasis-node/cmd/debug/txsource/workload/governance.go
  go/oasis-node/cmd/debug/txsource/workload/registration.go
  go/oasis-node/cmd/registry/entity/entity.go
  go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go
  go/registry/gen_vectors/main.go
  go/registry/tests/tester.go
  go/staking/gen_vectors/main.go
  go/upgrade/api/api.go
  go/upgrade/api/api_test.go
  go/upgrade/migrations/dummy.go
Labels: c:breaking/consensus, c:common, c:governance, c:testing

#3851 go/worker/compute/executor: Enable schedule_check_tx.enabled by default
  .changelog/3851.feature.md
  go/upgrade/api/api.go
  go/worker/compute/executor/init.go
Labels: c:runtime/compute

#3853 docs: Update Security document
  .changelog/3853.doc.md
  SECURITY.md
  docs/index.md
  docs/toc.md
Labels: c:docs, c:security

#3855 changelog and docs mini fixes
  .changelog/3853.doc.md
  .changelog/3855.trivial.md
  docs/consensus/test-vectors.md
Labels: c:docs

#3858 go/oasis-node/cmd/genesis: Display doc's hash and SHA256 checksum with check command
  .changelog/3858.feature.md
  go/oasis-node/cmd/genesis/genesis.go
Labels: c:cli

#3874 [BACKPORT/21.1.x] Apply upgrade proposals directly from governance consensus application
  .changelog/3870.bugfix.md
  go/consensus/tendermint/abci/mux.go
  go/consensus/tendermint/api/api.go
  go/consensus/tendermint/apps/governance/governance.go
  go/consensus/tendermint/full/full.go
  go/consensus/tendermint/full/helpers.go
  go/oasis-node/cmd/node/node.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/oasis.go
  go/worker/upgrade/worker.go
Labels: c:backport

#3873 [BACKPORT/20.12.x] go/consensus: Gracefully handle halt
  .changelog/3755.bugfix.md
  .changelog/3873.bugfix.md
  .changelog/3877.internal.md
  go/.nancy-ignore
  go/common/grpc/grpc.go
  go/consensus/api/api.go
  go/consensus/tendermint/abci/mux.go
  go/consensus/tendermint/full/full.go
  go/consensus/tendermint/full/helpers.go
  go/consensus/tendermint/seed/seed.go
  go/go.mod
  go/go.sum
  go/oasis-node/cmd/common/background/service_manager.go
  go/oasis-node/cmd/node/node.go
  go/oasis-test-runner/log/log.go
Labels: c:backport

#3883 [BACKPORT/21.1.x] go/oasis-node: Dump correct block height on halt
  .changelog/3755.bugfix.2.md
  .changelog/3877.internal.md
  go/.nancy-ignore
  go/oasis-node/cmd/node/node.go
Labels: c:backport

#3901 [BACKPORT/21.1.x] Minor runtime worker fixes
  .changelog/3889.bugfix.md
  .changelog/3899.bugfix.md
  go/worker/common/committee/node.go
  go/worker/storage/committee/utils.go
Labels: c:backport

#3891 Release process enhancements
  .changelog/3891.docs.md
  .changelog/3891.internal.md
  .changelog/template.md.j2
  docs/release-process.md
Labels: c:ops

#3896 go/consensus/tendermint: Update nonce post-execution during CheckTx
  .changelog/3896.bugfix.md
  go/consensus/tendermint/abci/mux.go
  go/consensus/tendermint/api/api.go
  go/consensus/tendermint/apps/staking/auth.go
Labels: c:consensus/tendermint
