Repository oasisprotocol/oasis-core, pull requests merged in 2021-01, with the labels that each got.

#3593 go/oasis-node/txsource: Fix event validation in queries workload
  .changelog/3593.internal.md
  go/oasis-node/cmd/debug/txsource/workload/queries.go
Labels: c:bug, c:testing

#3573 runtime: Various changes needed for the Runtime SDK
  .changelog/3573.breaking.1.md
  .changelog/3573.feature.1.md
  .changelog/3573.feature.2.md
  go/oasis-node/cmd/debug/txsource/workload/runtime.go
  go/runtime/client/api/api.go
  go/runtime/client/api/grpc.go
  go/runtime/client/client.go
  go/runtime/client/tests/tester.go
  go/runtime/host/protocol/types.go
  go/worker/compute/executor/committee/node.go
  runtime/src/common/version.rs
  runtime/src/dispatcher.rs
  runtime/src/protocol.rs
  runtime/src/transaction/context.rs
  runtime/src/transaction/dispatcher.rs
  runtime/src/transaction/macros.rs
  runtime/src/transaction/types.rs
  runtime/src/types.rs
Labels: c:breaking/runtime

#3548 Modify runtime descriptors to support ADR 0004
  .changelog/3450.breaking.2.md
  .changelog/3450.breaking.md
  .changelog/3450.internal.md
  docs/consensus/genesis.md
  docs/consensus/registry.md
  go/consensus/tendermint/apps/keymanager/genesis.go
  go/consensus/tendermint/apps/registry/genesis.go
  go/consensus/tendermint/apps/registry/registry.go
  go/consensus/tendermint/apps/registry/state/state.go
  go/consensus/tendermint/apps/registry/state/state_test.go
  go/consensus/tendermint/apps/registry/transactions.go
  go/consensus/tendermint/apps/registry/transactions_test.go
  go/consensus/tendermint/apps/scheduler/scheduler.go
  go/consensus/tendermint/apps/supplementarysanity/checks.go
  go/consensus/tendermint/tests/genesis/genesis.go
  go/genesis/genesis_test.go
  go/oasis-net-runner/fixtures/default.go
  go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
  go/oasis-node/cmd/debug/txsource/workload/registration.go
  go/oasis-node/cmd/genesis/genesis.go
  go/oasis-node/cmd/ias/auth_genesis.go
  go/oasis-node/cmd/registry/runtime/runtime.go
  go/oasis-node/node_test.go
  go/oasis-test-runner/oasis/cli/registry.go
  go/oasis-test-runner/oasis/runtime.go
  go/oasis-test-runner/scenario/e2e/registry_cli.go
  go/oasis-test-runner/scenario/e2e/runtime/history_reindex.go
  go/oasis-test-runner/scenario/e2e/runtime/multiple_runtimes.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime.go
  go/oasis-test-runner/scenario/e2e/runtime/storage_sync_from_registered.go
  go/oasis-test-runner/scenario/e2e/runtime/txsource.go
  go/registry/api/api.go
  go/registry/api/runtime.go
  go/registry/api/sanity_check.go
  go/registry/tests/tester.go
  go/roothash/api/commitment/pool_test.go
  go/scheduler/tests/tester.go
  go/staking/api/slashing.go
Labels: c:breaking/cfg, c:breaking/consensus, c:breaking/runtime

#3610 go/upgrade: use ProtocolVersions as internal upgrade identifier
  .changelog/3579.breaking.md
  go/common/version/version.go
  go/common/version/version_test.go
  go/consensus/tendermint/apps/governance/genesis_test.go
  go/consensus/tendermint/apps/governance/governance_test.go
  go/consensus/tendermint/apps/governance/state/state_test.go
  go/consensus/tendermint/apps/governance/transactions_test.go
  go/consensus/tests/tester.go
  go/control/api/api.go
  go/control/api/grpc.go
  go/control/control.go
  go/genesis/genesis_test.go
  go/governance/api/api_test.go
  go/governance/gen_vectors/main.go
  go/governance/tests/tester.go
  go/oasis-node/cmd/control/control.go
  go/oasis-node/cmd/debug/txsource/workload/governance.go
  go/oasis-node/cmd/debug/txsource/workload/queries.go
  go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go
  go/oasis-test-runner/scenario/e2e/upgrade.go
  go/oasis-test-runner/scenario/e2e/upgrade_cancel.go
  go/upgrade/api/api.go
  go/upgrade/api/api_test.go
  go/upgrade/dummy.go
  go/upgrade/upgrade.go
Labels: c:breaking/consensus

#3637 [BACKPORT/20.12.x] Bump arc-swap and smallvec
  .changelog/3511.internal.md
  .changelog/3604.internal.2.md
  Cargo.lock
Labels: c:backport

#3636 go/oasis-test-runner/txsource: Decrease MinPoolSize for restarts
  .changelog/3636.internal.md
  go/oasis-test-runner/scenario/e2e/runtime/txsource.go
Labels: c:bug, c:testing

#3650 go/oasis-test-runner/txsource: Also decrease MinPoolSize for storage
  .changelog/3650.trivial.md
  go/oasis-test-runner/scenario/e2e/runtime/txsource.go
Labels: c:bug, c:testing

#3660 go/registry: Fix node sanity checks
  .changelog/3660.breaking.md
  go/consensus/tendermint/apps/supplementarysanity/checks.go
  go/genesis/api/sanity_check.go
  go/registry/api/api.go
  go/registry/api/sanity_check.go
Labels: c:bug, c:registry

#3663 tests: Fix potential key clash in the confidential test KV runtime
  .changelog/3663.internal.md
  tests/runtimes/simple-keyvalue/src/main.rs
Labels: c:bug, c:testing
