Repository oasisprotocol/oasis-core, pull requests merged in 2021-06, with the labels that each got.

#3991 docs: Add missing gRPC services and beacon service
  .changelog/3991.doc.md
  docs/consensus/beacon.md
  docs/oasis-node/rpc.md
Labels: c:docs

#4010 go/storage/mkvs/checkpoint: Checkpoint in descending order
  .changelog/4010.bugfix.2.md
  .changelog/4010.bugfix.md
  go/common/badger/helpers.go
  go/common/badger/migrate.go
  go/consensus/tendermint/abci/state.go
  go/oasis-node/cmd/debug/beacon/beacon.go
  go/storage/mkvs/checkpoint/checkpointer.go
  go/storage/mkvs/checkpoint/checkpointer_test.go
Labels: c:bug

#4013 [BACKPORT/21.2.x] Backport of multiple bugfixes
  .changelog/4009.bugfix.md
  .changelog/4010.bugfix.2.md
  .changelog/4010.bugfix.md
  go/common/badger/helpers.go
  go/common/badger/migrate.go
  go/consensus/tendermint/abci/state.go
  go/oasis-net-runner/fixtures/default.go
  go/oasis-node/cmd/debug/beacon/beacon.go
  go/storage/mkvs/checkpoint/checkpointer.go
  go/storage/mkvs/checkpoint/checkpointer_test.go
Labels: c:backport

#4015 [BACKPORT/21.2.x] go/staking: Add DebondingStartEscrowEvent
  .changelog/4014.feature.md
  go/consensus/tendermint/apps/staking/api.go
  go/consensus/tendermint/apps/staking/transactions.go
  go/consensus/tendermint/staking/staking.go
  go/staking/api/api.go
  go/staking/tests/tester.go
Labels: c:backport

#4017 docs: Don't prefix backport branches with stable/* in Release Process
  .changelog/4017.trivial.md
  docs/release-process.md
Labels: c:docs, c:ops

#4029 [BACKPORT/21.2.x] Multiple dependency updates and fixes
  .changelog/4003.internal.md
  .changelog/4021.internal.md
  .changelog/4022.trivial.md
  .changelog/4026.internal.md
  Cargo.lock
  Cargo.toml
  go/go.mod
  go/go.sum
  runtime/Cargo.toml
  runtime/src/common/bytes.rs
  runtime/src/common/sgx/avr.rs
  runtime/src/lib.rs
Labels: c:backport

#4033 go/consensus/tendermint/apps/staking: Fix emitted reward events
  .changelog/4033.bugfix.md
  .changelog/4033.internal.md
  go/beacon/api/pvss.go
  go/consensus/tendermint/api/api.go
  go/consensus/tendermint/api/context.go
  go/consensus/tendermint/apps/beacon/backend_pvss.go
  go/consensus/tendermint/apps/governance/api.go
  go/consensus/tendermint/apps/governance/governance.go
  go/consensus/tendermint/apps/governance/transactions.go
  go/consensus/tendermint/apps/scheduler/scheduler.go
  go/consensus/tendermint/apps/staking/api.go
  go/consensus/tendermint/apps/staking/fees.go
  go/consensus/tendermint/apps/staking/staking.go
  go/consensus/tendermint/apps/staking/state/gas.go
  go/consensus/tendermint/apps/staking/state/state.go
  go/consensus/tendermint/apps/staking/state/state_test.go
  go/consensus/tendermint/apps/staking/transactions.go
  go/consensus/tendermint/beacon/beacon.go
  go/consensus/tendermint/governance/governance.go
  go/consensus/tendermint/staking/staking.go
  go/governance/api/api.go
  go/staking/api/api.go
Labels: c:bug

#4036 [BACKPORT/21.2.x] go/consensus/tendermint/apps/staking: Fix emitted reward events
  .changelog/4033.bugfix.md
  .changelog/4033.internal.md
  go/beacon/api/pvss.go
  go/consensus/tendermint/api/api.go
  go/consensus/tendermint/api/context.go
  go/consensus/tendermint/apps/beacon/backend_pvss.go
  go/consensus/tendermint/apps/governance/api.go
  go/consensus/tendermint/apps/governance/governance.go
  go/consensus/tendermint/apps/governance/transactions.go
  go/consensus/tendermint/apps/scheduler/scheduler.go
  go/consensus/tendermint/apps/staking/api.go
  go/consensus/tendermint/apps/staking/fees.go
  go/consensus/tendermint/apps/staking/staking.go
  go/consensus/tendermint/apps/staking/state/gas.go
  go/consensus/tendermint/apps/staking/state/state.go
  go/consensus/tendermint/apps/staking/state/state_test.go
  go/consensus/tendermint/apps/staking/transactions.go
  go/consensus/tendermint/beacon/beacon.go
  go/consensus/tendermint/governance/governance.go
  go/consensus/tendermint/staking/staking.go
  go/governance/api/api.go
  go/staking/api/api.go
Labels: c:backport

#4037 badger/migration: keep only last version when migrating non-managed DB
  .changelog/4037.bugfix.md
  go/common/badger/helpers.go
  go/common/badger/migrate.go
  go/oasis-node/cmd/node/node.go
Labels: s:ready-ci

#4045 [BACKPORT/21.2.x] Multiple dependency updates and fixes
  .buildkite/code.pipeline.yml
  .changelog/4024.feature.2.md
  .changelog/4024.feature.3.md
  .changelog/4024.feature.md
  .changelog/4037.bugfix.md
  .changelog/4037.cfg.md
  .changelog/4039.trivial.md
  .changelog/4040.feature.md
  .changelog/4041.cfg.md
  .changelog/4042.trivial.md
  .github/workflows/ci-reproducibility.yml
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
  .goreleaser.yml
  docker/development/Dockerfile
  docs/setup/building.md
  docs/setup/prerequisites.md
  go/Makefile
  go/common/badger/helpers.go
  go/common/badger/migrate.go
  go/oasis-net-runner/fixtures/default.go
  go/oasis-node/cmd/node/node.go
  go/oasis-test-runner/oasis/client.go
  go/oasis-test-runner/oasis/fixture.go
  go/oasis-test-runner/oasis/keymanager.go
  runtime-loader/Cargo.toml
  runtime-loader/bin/main.rs
  runtime-loader/src/lib.rs
Labels: c:backport

#4025 Updates useful for oasis-sdk#96
  .changelog/4025.cfg.md
  .changelog/4025.feature.md
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/fixture.go
  go/oasis-test-runner/oasis/oasis.go
  go/worker/common/p2p/init.go
  go/worker/common/p2p/p2p.go
Labels: s:ready-ci

#4051 [BACKPORT/21.2.x] ci: Fix dirty Git state in release workflow
  .changelog/4050.internal.md
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
Labels: c:backport

#4052 github: Unify jemalloc installation with GoReleaser installation
  .changelog/4052.internal.md
  .github/workflows/ci-reproducibility.yml
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
Labels: c:ops

#4053 [BACKPORT/21.2.x] github: Unify jemalloc installation with GoReleaser installation
  .changelog/4052.internal.md
  .github/workflows/ci-reproducibility.yml
  .github/workflows/release-dev.yml
  .github/workflows/release.yml
Labels: c:backport

#4059 go/runtime/host/sandbox: Prevent restart storm after 10m
  .changelog/4059.bugfix.md
  .changelog/4059.internal.md
  go/common/backoff/backoff.go
  go/consensus/api/submission.go
  go/runtime/client/submitter.go
  go/runtime/host/sandbox/sandbox.go
  go/runtime/tagindexer/tagindexer.go
  go/worker/beacon/worker.go
  go/worker/common/p2p/dispatch.go
  go/worker/common/p2p/peermgmt.go
  go/worker/keymanager/worker.go
  go/worker/registration/worker.go
  go/worker/storage/committee/utils.go
Labels: c:bug

#4063 [BACKPORT/21.2.x] Multiple backports
  .changelog/4059.bugfix.md
  .changelog/4059.internal.md
  .changelog/4061.bugfix.md
  .changelog/4061.internal.md
  go/common/backoff/backoff.go
  go/consensus/api/submission.go
  go/oasis-node/cmd/node/node.go
  go/runtime/client/submitter.go
  go/runtime/host/sandbox/sandbox.go
  go/runtime/registry/registry.go
  go/runtime/tagindexer/tagindexer.go
  go/storage/client/client.go
  go/storage/client/init.go
  go/worker/beacon/worker.go
  go/worker/common/committee/group.go
  go/worker/common/committee/node.go
  go/worker/common/p2p/dispatch.go
  go/worker/common/p2p/peermgmt.go
  go/worker/compute/executor/committee/node.go
  go/worker/keymanager/worker.go
  go/worker/registration/worker.go
  go/worker/storage/committee/utils.go
Labels: c:backport

#4072 go/worker/storage: Add missing timeout for operations
  .changelog/4072.bugfix.1.md
  .changelog/4072.bugfix.2.md
  go/worker/storage/committee/checkpoint_sync.go
  go/worker/storage/committee/node.go
Labels: c:bug, c:runtime, c:storage

#4073 [BACKPORT/21.2.x] go/worker/storage: Add missing timeout for operations
  .changelog/4072.bugfix.1.md
  .changelog/4072.bugfix.2.md
  go/worker/storage/committee/checkpoint_sync.go
  go/worker/storage/committee/node.go
Labels: c:backport

#4077 [BACKPORT/21.2.x] go/consensus/tendermint: Fix last retained version query
  .changelog/4060.bugfix.md
  go/consensus/tendermint/abci/prune.go
  go/consensus/tendermint/full/full.go
  go/oasis-test-runner/scenario/e2e/consensus_state_sync.go
Labels: c:backport

#4082 [BACKPORT/21.2.x] multiple backports
  .changelog/4081.bugfix.md
  .changelog/4083.bugfix.md
  go/ias/proxy/client/client.go
  go/worker/compute/executor/committee/node.go
Labels: c:backport

#4084 [BACKPORT/21.2.x] go/worker/storage: Force checkpoint sync when block info unavailable
  .changelog/4080.bugfix.md
  .changelog/4080.feature.md
  .changelog/4080.internal.1.md
  .changelog/4080.internal.2.md
  .changelog/4080.internal.3.md
  go/consensus/api/api.go
  go/consensus/tendermint/abci/state.go
  go/consensus/tendermint/api/state.go
  go/consensus/tendermint/full/full.go
  go/consensus/tendermint/seed/seed.go
  go/keymanager/client/client.go
  go/oasis-node/cmd/debug/dumpdb/dumpdb.go
  go/oasis-node/node_test.go
  go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go
  go/runtime/client/client.go
  go/runtime/committee/committee.go
  go/runtime/nodes/runtime.go
  go/runtime/nodes/versioned.go
  go/runtime/registry/registry.go
  go/storage/client/init.go
  go/storage/client/tests/tests.go
  go/storage/mkvs/checkpoint/checkpointer.go
  go/storage/mkvs/checkpoint/checkpointer_test.go
  go/worker/common/committee/group.go
  go/worker/common/committee/node.go
  go/worker/keymanager/handler.go
  go/worker/keymanager/watcher.go
  go/worker/storage/committee/node.go
Labels: c:backport

#4067 go/common/errors: expose all grpc errors as coded
  .changelog/4067.feature.md
  go/common/errors/errors.go
  go/common/errors/errors_test.go
Labels: s:ready-ci

#4085 consensus/tendermint: Handle validator fetching error in GetStatus()
  .changelog/4085.bugfix.md
  go/consensus/tendermint/full/full.go
Labels: c:cli, c:consensus/tendermint

#4094 [BACKPORT/21.2.x] Multiple backports
  .changelog/4085.bugfix.md
  .changelog/4093.bugfix.2.md
  .changelog/4093.bugfix.md
  go/consensus/tendermint/full/full.go
  go/storage/api/api.go
  go/storage/api/mux.go
  go/storage/api/mux_test.go
  go/worker/common/committee/group.go
  go/worker/storage/synced_storage.go
Labels: c:backport

#4097 [BACKPORT/21.2.x] go/storage/mkvs/checkpoint: Determine next offset correctly
  .changelog/4096.bugfix.md
  go/storage/mkvs/checkpoint/checkpoint_test.go
  go/storage/mkvs/checkpoint/chunk.go
Labels: c:backport
