Repository oasisprotocol/oasis-core, pull requests merged in 2021-12, with the labels that each got.

#4386 runtime: Propagate panics during transaction/local RPC/policy dispatch
  .changelog/4386.bugfix.md
  runtime/src/dispatcher.rs
Labels: c:runtime

#4387 go/worker/storage: Checkpoint correct round on consensus checkpoint
  .changelog/4387.bugfix.1.md
  .changelog/4387.bugfix.2.md
  go/runtime/client/client.go
  go/storage/mkvs/checkpoint/checkpointer.go
  go/worker/storage/committee/node.go
Labels: c:storage, c:bug

#4388 [BACKPORT/21.3.x] go/worker/storage: Checkpoint correct round on consensus checkpoint
  .changelog/4387.bugfix.1.md
  .changelog/4387.bugfix.2.md
  go/runtime/client/client.go
  go/storage/mkvs/checkpoint/checkpointer.go
  go/worker/storage/committee/node.go
Labels: c:backport

#4395 tests/workload/runtime: Wait for 3rd epoch for compute nodes to be up
  .changelog/4395.internal.md
  go/oasis-node/cmd/debug/txsource/workload/runtime.go
Labels: c:testing

#4327 ADR 0011: Incoming Runtime Messages
  .changelog/4327.doc.md
  docs/adr/0011-incoming-runtime-messages.md
  docs/adr/index.md
Labels: c:docs/adr

#4397 go/storage/client: Catch GetDiff errors early
  .changelog/4397.bugfix.md
  go/storage/client/client.go
Labels: c:bug

#4398 [BACKPORT/21.3.x] go/storage/client: Catch GetDiff errors early
  .changelog/4397.bugfix.md
  go/storage/client/client.go
Labels: c:backport

#4392 ADR-0012: Runtime message results
  .changelog/4392.doc.md
  docs/adr/0012-runtime-message-results.md
  docs/adr/index.md
Labels: c:docs/adr

#4403 go/worker/storage: Limit number of rounds to fetch before applying them
  .changelog/4403.bugfix.md
  go/worker/storage/committee/node.go
Labels: c:storage, c:runtime

#4404 [BACKPORT/21.3.x] go/worker/storage: Limit number of rounds to fetch before applying them
  .changelog/4403.bugfix.md
  go/worker/storage/committee/node.go
Labels: c:backport

#4411 go/storage/api: Make metrics wrapper return proper types
  .changelog/4411.bugfix.md
  Cargo.lock
  go/storage/api/metrics.go
  go/worker/storage/init.go
  keymanager-client/Cargo.toml
  keymanager-lib/Cargo.toml
  runtime/Cargo.toml
Labels: c:bug

#4412 [BACKPORT/21.3.x] go/storage/api: Make metrics wrapper return proper types
  .changelog/4411.bugfix.md
  Cargo.lock
  go/storage/api/metrics.go
  go/worker/storage/init.go
  keymanager-client/Cargo.toml
  keymanager-lib/Cargo.toml
  runtime/Cargo.toml
Labels: c:backport
