Repository oasisprotocol/oasis-core, pull requests merged in 2022-05, with the labels that each got.

#4710 go/runtime/config: error if SGX loader required but not configured
  .changelog/4710.bugfix.md
  go/runtime/registry/config.go
Labels: s:ready-ci

#4725 go/worker/keymanager: Fix crash on capability TEE updates
  .changelog/4725.bugfix.md
  go/worker/keymanager/worker.go
Labels: c:bug

#4726 go/worker/registration: Only register once epoch is known
  .changelog/4726.bugfix.md
  go/consensus/tendermint/beacon/beacon.go
  go/roothash/tests/tester.go
  go/worker/registration/worker.go
Labels: c:bug

#4721 [BACKPORT/22.1.x] Multiple backports
  .buildkite/code.pipeline.yml
  .changelog/4700.feature.md
  .changelog/4702.feature.md
  .changelog/4707.internal.md
  .changelog/4710.bugfix.md
  .changelog/4715.feature.md
  .changelog/4724.feature.md
  .changelog/4725.bugfix.md
  .changelog/4726.bugfix.md
  .github/workflows/release.yml
  docs/oasis-node/metrics.md
  go/common/dynlib/cache.go
  go/consensus/tendermint/beacon/beacon.go
  go/oasis-node/cmd/node/node.go
  go/oasis-node/cmd/node/unsafe_reset.go
  go/oasis-test-runner/oasis/cli/cli.go
  go/oasis-test-runner/scenario/e2e/e2e.go
  go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
  go/registry/api/api.go
  go/roothash/tests/tester.go
  go/runtime/registry/config.go
  go/runtime/txpool/metrics.go
  go/runtime/txpool/txpool.go
  go/worker/common/committee/keymanager.go
  go/worker/common/committee/node.go
  go/worker/common/committee/runtime_host.go
  go/worker/compute/executor/committee/node.go
  go/worker/keymanager/worker.go
  go/worker/registration/worker.go
Labels: c:backport

#4730 [BACKPORT/22.1.x] go/runtime/registry: Refresh key manager policy on runtime changes
  .changelog/4729.bugfix.md
  go/runtime/registry/host.go
  keymanager-client/src/client.rs
  tests/runtimes/simple-keymanager/src/api.rs
Labels: c:backport

#4734 go/runtime/config: fix SGX provisioner check
  .changelog/4734.bugfix.md
  go/runtime/registry/config.go
Labels: s:ready-ci

#4741 runtime: Verify RAK in consensus state when serving requests
  .changelog/4741.bugfix.md
  .changelog/4741.feature.md
  go/common/node/node_test.go
  go/consensus/tendermint/apps/registry/state/interop/interop.go
  go/storage/mkvs/interop/fixtures/consensus_mock.go
  runtime/src/common/crypto/signature.rs
  runtime/src/common/version.rs
  runtime/src/consensus/registry.rs
  runtime/src/consensus/roothash.rs
  runtime/src/consensus/state/beacon.rs
  runtime/src/consensus/state/mod.rs
  runtime/src/consensus/state/registry.rs
  runtime/src/consensus/state/staking.rs
  runtime/src/consensus/tendermint/verifier.rs
  runtime/src/protocol.rs
Labels: s:ready-ci

#4752 go/common/sgx/pcs: Add PCS HTTP client
  .changelog/4752.internal.md
  go/common/sgx/pcs/http.go
  go/common/sgx/pcs/pcs.go
  go/common/sgx/pcs/quote.go
  go/runtime/host/sgx/ecdsa.go
  go/runtime/host/sgx/sgx.go
  go/runtime/registry/config.go
  go/worker/client/committee/node.go
  go/worker/common/committee/node.go
  go/worker/compute/executor/committee/node.go
  go/worker/storage/committee/node.go
Labels: c:common

#4757 runtime: Add support for reporting EnclaveRPC peer feedback
  .changelog/4757.feature.md
  client/src/enclave_rpc/client.rs
  client/src/enclave_rpc/transport.rs
  go/runtime/enclaverpc/api/api.go
  go/runtime/host/protocol/types.go
  go/runtime/keymanager/api/api.go
  go/runtime/registry/host.go
  go/worker/common/committee/keymanager.go
  go/worker/common/committee/node.go
  go/worker/keymanager/handler.go
  go/worker/keymanager/worker.go
  runtime/src/enclave_rpc/types.rs
  runtime/src/types.rs
Labels: c:runtime

#4758 [BACKPORT/22.1.x] Multiple backports
  .buildkite/go/nancy_audit.sh
  .changelog/4709.feature.md
  .changelog/4754.internal.md
  .changelog/4757.feature.md
  .changelog/4762.trivial.md
  client/src/enclave_rpc/client.rs
  client/src/enclave_rpc/transport.rs
  docker/development/Dockerfile
  go/.nancy-ignore
  go/common/logging/logging.go
  go/go.mod
  go/go.sum
  go/registry/api/runtime.go
  go/runtime/enclaverpc/api/api.go
  go/runtime/host/logger.go
  go/runtime/host/logger_test.go
  go/runtime/host/protocol/types.go
  go/runtime/host/sandbox/sandbox.go
  go/runtime/host/sgx/sgx.go
  go/runtime/keymanager/api/api.go
  go/runtime/registry/host.go
  go/worker/common/committee/keymanager.go
  go/worker/common/committee/node.go
  go/worker/keymanager/handler.go
  go/worker/keymanager/worker.go
  runtime/src/enclave_rpc/types.rs
  runtime/src/types.rs
Labels: c:backport

#4765 go: Bump libp2p to 0.20.0
  .changelog/4765.internal.md
  go/go.mod
  go/go.sum
Labels: c:deps

#4767 README.md: Fix broken links
  .changelog/4767.doc.md
  README.md
Labels: c:docs
