Repository oasisprotocol/oasis-core, pull requests merged in 2022-04, with the labels that each got.

#4623 scheduler: Improve "more nodes = more better" fairness problems
  .changelog/4623.breaking.md
  go/consensus/tendermint/apps/scheduler/debug_force.go
  go/consensus/tendermint/apps/scheduler/shuffle.go
Labels: c:breaking/consensus

#4626 runtime: Bump Rust dependencies
  .changelog/4626.trivial.md
  Cargo.lock
  runtime/src/consensus/tendermint/mod.rs
Labels: c:runtime, c:deps

#4633 go/worker/compute: Always include resolved transactions
  .changelog/4633.bugfix.md
  go/worker/compute/executor/committee/batch.go
  go/worker/compute/executor/committee/transactions.go
Labels: c:bug

#4635 [BACKPORT/22.1.x] go/worker/compute: Always include resolved transactions
  .changelog/4633.bugfix.md
  go/worker/compute/executor/committee/batch.go
  go/worker/compute/executor/committee/transactions.go
Labels: c:backport

#4637 [BACKPORT/22.1.x] go/control: Show the debug option statuses in the control output
  .changelog/4634.feature.md
  go/control/api/api.go
  go/control/control.go
Labels: c:backport

#4639 [BACKPORT/22.1.x] go/runtime/txpool: Fix crash on early access
  .changelog/4638.bugfix.md
  go/runtime/txpool/txpool.go
Labels: c:backport

#4640 go/worker/compute: Improve proposed transaction handling
  .changelog/4640.bugfix.md
  .changelog/4640.feature.md
  go/runtime/txpool/txpool.go
  go/worker/common/p2p/rpc/client.go
  go/worker/common/p2p/txsync/client.go
  go/worker/common/p2p/txsync/protocol.go
  go/worker/compute/executor/committee/batch.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/transactions.go
  runtime/src/config.rs
  runtime/src/dispatcher.rs
Labels: c:bug

#4642 [BACKPORT/22.1.x] go/worker/compute: Improve proposed transaction handling
  .changelog/4640.bugfix.md
  .changelog/4640.feature.md
  Cargo.lock
  go/runtime/txpool/txpool.go
  go/worker/common/p2p/rpc/client.go
  go/worker/common/p2p/txsync/client.go
  go/worker/common/p2p/txsync/protocol.go
  go/worker/compute/executor/committee/batch.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/transactions.go
  keymanager-client/Cargo.toml
  keymanager-lib/Cargo.toml
  runtime-loader/Cargo.toml
  runtime/Cargo.toml
  runtime/src/config.rs
  runtime/src/dispatcher.rs
  tools/Cargo.toml
Labels: c:backport

#4645 [BACKPORT/22.1.x] go/runtime/host/sgx: Don't trample over the actual error
  .changelog/4644.trivial.md
  go/runtime/host/sgx/sgx.go
Labels: c:backport

#4647 go/runtime/host: Always emit StoppedEvent on stop
  .changelog/4647.bugfix.md
  go/runtime/host/sandbox/sandbox.go
Labels: c:bug

#4649 [BACKPORT/22.1.x] go/runtime/host: Always emit StoppedEvent on stop
  .changelog/4647.bugfix.md
  go/runtime/host/sandbox/sandbox.go
Labels: c:backport

#4651 [BACKPORT/22.1.x] go/worker/common/p2p: Make sure P2P stops before service cleanup runs
  .changelog/4650.bugfix.md
  go/oasis-node/cmd/debug/byzantine/p2p.go
  go/oasis-node/cmd/node/node.go
  go/worker/common/p2p/p2p.go
Labels: c:backport

#4650 go/worker/common/p2p: Make sure P2P stops before service cleanup runs
  .changelog/4650.bugfix.md
  go/oasis-node/cmd/debug/byzantine/p2p.go
  go/oasis-node/cmd/node/node.go
  go/worker/common/p2p/p2p.go
Labels: c:bug, c:p2p

#4654 [BACKPORT/22.1.x]: go/consensus/api/transactions: Fix OpenRawTransactions
  .changelog/4653.trivial.md
  go/consensus/api/transaction/transaction.go
Labels: c:backport

#4608 [BACKPORT/21.3.x]: Add archive mode support
  .changelog/4539.feature.md
  .changelog/4571.bugfix.md
  go/consensus/api/api.go
  go/consensus/api/submission.go
  go/consensus/api/transaction/transaction.go
  go/consensus/tendermint/api/api.go
  go/consensus/tendermint/full/archive.go
  go/consensus/tendermint/full/common.go
  go/consensus/tendermint/full/full.go
  go/consensus/tendermint/full/light.go
  go/consensus/tendermint/full/services.go
  go/consensus/tendermint/seed/seed.go
  go/consensus/tendermint/tendermint.go
  go/oasis-node/cmd/node/node.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/fixture.go
  go/oasis-test-runner/oasis/oasis.go
  go/oasis-test-runner/scenario/e2e/runtime/archive_api.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime.go
  go/upgrade/upgrade.go
  go/worker/registration/worker.go
Labels: s:ready-ci

#4665 go/runtime/txpool: Limit outstanding transactions per sender
  .changelog/4665.breaking.md
  .changelog/4665.feature.md
  go/go.mod
  go/go.sum
  go/runtime/host/helpers.go
  go/runtime/host/mock/mock.go
  go/runtime/host/protocol/types.go
  go/runtime/transaction/transaction.go
  go/runtime/txpool/check_queue.go
  go/runtime/txpool/check_queue_test.go
  go/runtime/txpool/priority_queue.go
  go/runtime/txpool/priority_queue_test.go
  go/runtime/txpool/schedule_queue.go
  go/runtime/txpool/schedule_queue_test.go
  go/runtime/txpool/transaction.go
  go/runtime/txpool/txpool.go
  go/worker/compute/executor/committee/batch.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/transactions.go
  runtime/src/dispatcher.rs
  runtime/src/transaction/dispatcher.rs
  runtime/src/types.rs
  tests/runtimes/simple-keyvalue/src/main.rs
Labels: c:runtime/scheduler

#4671 go/worker/storage: Make checkpoint sync peer selection smarter
  .changelog/4671.feature.md
  .changelog/4671.internal.md
  go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go
  go/storage/mkvs/checkpoint/checkpointer.go
  go/worker/common/p2p/rpc/client.go
  go/worker/storage/committee/checkpoint_sync.go
  go/worker/storage/p2p/sync/client.go
Labels: c:storage

#4673 ci: E2E SGX tests fixes
  .changelog/4673.internal.md
  go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
  go/oasis-test-runner/scenario/e2e/runtime/txsource.go
Labels: s:ready-ci

#4683 go/worker/compute: Only advertise active version for TEE runtimes
  .changelog/4683.bugfix.md
  go/worker/compute/executor/committee/node.go
Labels: c:bug

#4687 go/runtime/host/sandbox: Properly handle clone3 in seccomp policy
  .changelog/4687.bugfix.md
  go/runtime/host/sandbox/process/seccomp_linux.go
Labels: c:bug

#4688 [BACKPORT/22.1.x] Multiple backports
  .changelog/4683.bugfix.md
  .changelog/4687.bugfix.md
  go/runtime/host/sandbox/process/seccomp_linux.go
  go/worker/compute/executor/committee/node.go
Labels: c:backport

#4689 [BACKPORT/22.1.x] go/worker/compute: Ensure trust root is verified before registering
  .changelog/4678.feature.md
  go/oasis-test-runner/scenario/e2e/runtime/trust_root.go
  go/runtime/host/helpers.go
  go/runtime/host/mock/mock.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/trust.go
Labels: c:backport

#4695 BACKPORT: go/worker/registration: add node status metrics
  .changelog/4686.feature.md
  docs/oasis-node/metrics.md
  go/worker/registration/worker.go
Labels: c:backport

#4694 runtime: verify consensus state integrity for queries
  .changelog/4694.feature.md
  runtime/src/dispatcher.rs
Labels: s:ready-ci

#4706 Bump more dependencies
  .changelog/4706.internal.md
  Cargo.lock
  go/go.mod
  go/go.sum
  runtime/Cargo.toml
  runtime/src/common/sgx/avr.rs
Labels: c:deps
