Repository oasisprotocol/oasis-core, pull requests merged in 2022-08, with the labels that each got.

#4877 go/worker/keymanager: Add key manager worker metrics
  .changelog/4877.feature.md
  docs/oasis-node/metrics.md
  go/worker/keymanager/init.go
  go/worker/keymanager/metrics.go
  go/worker/keymanager/p2p/metrics.go
  go/worker/keymanager/p2p/server.go
  go/worker/keymanager/worker.go
Labels: golang, c:instrumentation

#4883 go: Add key manager worker status to node status
  .changelog/4883.feature.md
  go/control/api/api.go
  go/control/control.go
  go/oasis-node/cmd/node/control.go
  go/worker/keymanager/api/api.go
  go/worker/keymanager/init.go
  go/worker/keymanager/status.go
  go/worker/keymanager/worker.go
Labels: golang

#4887 Issue #4886 - advancedtls Certificate options moved to IdentityOptions
  .changelog/4886.internal.md
  go/common/grpc/credentials.go
  go/go.mod
  go/go.sum
Labels: c:deps

#4892 oasis-node/cmd/genesis: Fix reading height argument
  .changelog/4892.bugfix.md
  go/oasis-node/cmd/genesis/genesis.go
Labels: golang

#4906 go: Bump go-libp2p to 0.22.0
  .changelog/4906.internal.md
  go/go.mod
  go/go.sum
  go/worker/common/p2p/api/api.go
  go/worker/common/p2p/api/crypto.go
  go/worker/common/p2p/dispatch.go
  go/worker/common/p2p/nop.go
  go/worker/common/p2p/p2p.go
  go/worker/common/p2p/peermgmt.go
  go/worker/common/p2p/rpc/client.go
  go/worker/common/p2p/rpc/nop.go
  go/worker/common/p2p/rpc/peermgmt.go
  go/worker/common/p2p/rpc/rpc.go
  go/worker/common/p2p/rpc/server.go
  go/worker/keymanager/api/api.go
  go/worker/keymanager/init.go
  go/worker/keymanager/p2p/client.go
  go/worker/keymanager/status.go
  go/worker/keymanager/worker.go
Labels: c:deps

#4905 [BACKPORT/22.1.x] go/runtime/registry: allow client nodes to run SGX
  .changelog/4832.feature.md
  go/runtime/registry/config.go
Labels: c:backport
