Repository oasisprotocol/oasis-core, pull requests merged in 2022-06, with the labels that each got.

#4571 Add archive mode support
  .changelog/4539.feature.md
  go/consensus/api/api.go
  go/consensus/api/api_test.go
  go/consensus/api/submission.go
  go/consensus/api/transaction/transaction.go
  go/consensus/tendermint/api/api.go
  go/consensus/tendermint/full/archive.go
  go/consensus/tendermint/full/common.go
  go/consensus/tendermint/full/full.go
  go/consensus/tendermint/full/light.go
  go/consensus/tendermint/full/services.go
  go/consensus/tendermint/seed/seed.go
  go/consensus/tendermint/tendermint.go
  go/oasis-node/cmd/node/node.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/fixture.go
  go/oasis-test-runner/oasis/oasis.go
  go/oasis-test-runner/scenario/e2e/runtime/archive_api.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime.go
  go/upgrade/upgrade.go
Labels: s:ready-ci

#4781 [BACKPORT/21.3.x] go/runtime/host/sandbox: Properly handle clone3 in seccomp policy
  .changelog/4687.bugfix.md
  go/runtime/host/sandbox/process/seccomp_linux.go
Labels: c:backport

#4782 go: Bump libp2p to 0.20.1 and libp2p-pubsub to 0.7.0
  .changelog/4782.internal.md
  go/go.mod
  go/go.sum
  go/worker/common/p2p/p2p.go
Labels: c:deps

#4790 go/common/quantity: Avoid side-effects on errors
  .changelog/4790.bugfix.md
  go/common/quantity/quantity.go
Labels: c:bug

#4792 [BACKPORT/22.1.x] common/crypto/signature/signers/remote: Support AF_LOCAL
  .changelog/4733.trivial.md
  go/common/crypto/signature/signers/remote/grpc.go
  go/oasis-node/cmd/common/signer/signer.go
Labels: c:backport

#4795 go/consensus/tendermint: Add `consensus.tendermint.halt_height`
  .changelog/4793.feature.md
  go/consensus/tendermint/abci/mux.go
  go/consensus/tendermint/abci/state.go
  go/consensus/tendermint/full/full.go
Labels: c:backport

#4799 go/oasis-test-runner/byzantine: Add primary+backup liveness test
  .changelog/4799.internal.md
  go/consensus/tendermint/apps/scheduler/debug_force.go
  go/consensus/tendermint/apps/scheduler/shuffle.go
  go/oasis-node/cmd/genesis/genesis.go
  go/oasis-test-runner/oasis/network.go
  go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime.go
  go/scheduler/api/api.go
Labels: c:testing

#4475 Document missing dependency (gcc-multilib) for Ubuntu setup
  .changelog/4475.doc.md
  docs/development-setup/prerequisites.md
Labels: s:ready-ci

#4809 go/consensus/tendermint/full: Unify started indicators
  .changelog/4809.trivial.md
  go/consensus/tendermint/full/archive.go
  go/consensus/tendermint/full/common.go
  go/consensus/tendermint/full/full.go
Labels: c:consensus/tendermint, c:bug

#4815 [BACKPORT/22.1.x] net-runner: Add --fixture.default.runtime.version
  .changelog/4813.feature.md
  .changelog/4816.trivial.md
  go/oasis-net-runner/fixtures/default.go
Labels: c:backport

#4823 go/consensus/tendermint: Make sure DBs are only closed during cleanup
  .changelog/4823.bugfix.md
  go/consensus/tendermint/db/closer.go
  go/consensus/tendermint/full/archive.go
  go/consensus/tendermint/full/common.go
  go/consensus/tendermint/full/full.go
  go/consensus/tendermint/full/light.go
Labels: c:consensus/tendermint, c:bug

#4826 [BACKPORT/22.1.x] go/oasis-node: allow km private peers
  .changelog/4821.feature.md
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/client.go
  go/oasis-test-runner/oasis/fixture.go
  go/oasis-test-runner/oasis/keymanager.go
  go/oasis-test-runner/oasis/oasis.go
  go/worker/keymanager/init.go
  go/worker/keymanager/worker.go
Labels: c:backport
