Repository oasisprotocol/oasis-core, pull requests merged in 2022-12, with the labels that each got.

#5093 [BACKPORT/22.2.x] go/runtime/registry: Fix watching policy updates
  .changelog/5092.bugfix.md
  go/runtime/registry/host.go
Labels: c:backport

#5094 runtime/src/protocol: Deserialize unknown rhp messages as invalid
  .changelog/5094.internal.md
  runtime/src/protocol.rs
Labels: c:runtime, rust

#5099 keymanager/src/runtime: Remove redundant public key options
  .changelog/5099.trivial.md
  keymanager/src/client/interface.rs
  keymanager/src/client/mock.rs
  keymanager/src/client/remote.rs
  keymanager/src/crypto/kdf.rs
  keymanager/src/runtime/methods.rs
  tests/runtimes/simple-keyvalue/src/methods.rs
Labels: c:keymgmt, rust

#5106 runtime: Bump tendermint-rs to 0.28.0
  .changelog/5106.internal.md
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/consensus/tendermint/mod.rs
  runtime/src/consensus/tendermint/verifier/mod.rs
Labels: c:deps

#5111 go/runtime/registry: Fix key manager (quote) policy updates
  .changelog/5111.bugfix.md
  go/runtime/registry/host.go
  keymanager/src/policy/cached.rs
  runtime/src/attestation.rs
  runtime/src/dispatcher.rs
  runtime/src/policy.rs
Labels: golang, c:bug, rust

#5112 go/registry: Add optional bundle checksum to runtime deployments
  .changelog/5112.breaking.md
  go/consensus/tendermint/apps/registry/state/interop/interop.go
  go/registry/api/runtime.go
  go/registry/api/runtime_test.go
  runtime/src/consensus/registry.rs
  runtime/src/consensus/state/beacon.rs
  runtime/src/consensus/state/keymanager.rs
  runtime/src/consensus/state/registry.rs
  runtime/src/consensus/state/staking.rs
Labels: c:breaking/consensus
