Repository oasisprotocol/oasis-core, pull requests merged in 2022-01, with the labels that each got.

#4429 go/runtime/transaction: Return transactions in batch order when queried
  .changelog/4429.bugfix.md
  go/runtime/transaction/transaction.go
  go/runtime/transaction/transaction_test.go
Labels: c:client, c:bug

#4430 [BACKPORT/21.3.x] go/runtime/transaction: Return transactions in batch order when queried
  .changelog/4429.bugfix.md
  go/runtime/transaction/transaction.go
  go/runtime/transaction/transaction_test.go
Labels: c:backport

#4431 go/runtime/scheduling: Allow a higher priority tx even if queue full
  .changelog/4431.feature.md
  go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
  go/runtime/scheduling/simple/txpool/tester.go
Labels: c:runtime/scheduler

#4433 [BACKPORT/21.3.x] go/runtime/scheduling: Allow a higher priority tx even if queue full
  .changelog/4431.feature.md
  go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
  go/runtime/scheduling/simple/txpool/tester.go
Labels: c:backport

#4441 [BACKPORT/21.3.x] deps: Switch to the upstream jsonrpc import
  .changelog/4439.bugfix.md
  Cargo.lock
  runtime/Cargo.toml
Labels: c:bug, c:deps, c:backport

#4448 [BACKPORT/21.3.x] runtime: Propagate panics during transaction/local RPC/policy dispatch
  .changelog/4386.bugfix.md
  runtime/src/dispatcher.rs
Labels: c:backport

#4446 [BACKPORT/21.3.x] Add support for runtime schedule control
  .changelog/4438.feature.md
  go/oasis-test-runner/scenario/e2e/runtime/keymanager_restart.go
  go/runtime/client/host.go
  go/runtime/host/host.go
  go/runtime/host/mock/mock.go
  go/runtime/host/protocol/connection.go
  go/runtime/host/protocol/connection_test.go
  go/runtime/host/protocol/types.go
  go/runtime/host/sandbox/sandbox.go
  go/runtime/registry/host.go
  go/runtime/scheduling/api/api.go
  go/runtime/scheduling/simple/simple.go
  go/runtime/scheduling/simple/txpool/api/api.go
  go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
  go/runtime/scheduling/simple/txpool/tester.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/runtime_host.go
  go/worker/compute/executor/committee/state.go
  runtime/src/config.rs
  runtime/src/dispatcher.rs
  runtime/src/protocol.rs
  runtime/src/transaction/dispatcher.rs
  runtime/src/types.rs
  tests/runtimes/simple-keyvalue/src/main.rs
Labels: c:backport

#4415 Incoming runtime messages (ADR 0011)
  .changelog/4415.breaking.md
  docs/adr/0011-incoming-runtime-messages.md
  go/common/namespace.go
  go/consensus/tendermint/api/context.go
  go/consensus/tendermint/apps/roothash/query.go
  go/consensus/tendermint/apps/roothash/roothash.go
  go/consensus/tendermint/apps/roothash/state/state.go
  go/consensus/tendermint/apps/roothash/transactions.go
  go/consensus/tendermint/apps/roothash/transactions_test.go
  go/consensus/tendermint/apps/staking/state/state.go
  go/consensus/tendermint/apps/staking/state/state_test.go
  go/consensus/tendermint/roothash/roothash.go
  go/consensus/tendermint/tests/genesis/genesis.go
  go/genesis/genesis_test.go
  go/oasis-node/cmd/debug/byzantine/executor.go
  go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
  go/oasis-node/cmd/debug/txsource/workload/runtime.go
  go/oasis-node/cmd/genesis/genesis.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_client_kv.go
  go/registry/api/runtime.go
  go/registry/tests/tester.go
  go/roothash/api/api.go
  go/roothash/api/api_test.go
  go/roothash/api/block/block.go
  go/roothash/api/block/header.go
  go/roothash/api/block/header_test.go
  go/roothash/api/commitment/executor.go
  go/roothash/api/commitment/executor_test.go
  go/roothash/api/commitment/pool_test.go
  go/roothash/api/grpc.go
  go/roothash/api/message/incoming_message.go
  go/roothash/tests/tester.go
  go/runtime/host/mock/mock.go
  go/runtime/host/protocol/types.go
  go/worker/compute/executor/committee/node.go
  runtime/src/consensus/registry.rs
  runtime/src/consensus/roothash.rs
  runtime/src/consensus/staking.rs
  runtime/src/dispatcher.rs
  runtime/src/transaction/dispatcher.rs
  runtime/src/types.rs
  tests/runtimes/simple-keyvalue/src/main.rs
Labels: c:breaking/consensus, c:breaking/runtime

#4454 [BACKPORT/21.3.x] go/runtime/scheduling: Attempt to continue scheduling
  .changelog/4453.bugfix.md
  go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
Labels: c:backport

#4453 go/runtime/scheduling: Attempt to continue scheduling
  .changelog/4453.bugfix.md
  go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
Labels: c:bug, c:runtime/scheduler

#4438 Add support for runtime schedule control
  .changelog/4438.feature.md
  go/oasis-test-runner/scenario/e2e/runtime/keymanager_restart.go
  go/runtime/host/host.go
  go/runtime/host/mock/mock.go
  go/runtime/host/protocol/connection.go
  go/runtime/host/protocol/connection_test.go
  go/runtime/host/protocol/types.go
  go/runtime/host/sandbox/sandbox.go
  go/runtime/registry/host.go
  go/runtime/scheduling/api/api.go
  go/runtime/scheduling/simple/simple.go
  go/runtime/scheduling/simple/txpool/api/api.go
  go/runtime/scheduling/simple/txpool/priorityqueue/priority_queue.go
  go/runtime/scheduling/simple/txpool/tester.go
  go/runtime/txpool/txpool.go
  go/worker/common/committee/runtime_host.go
  go/worker/compute/executor/committee/batch.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/state.go
  runtime/src/config.rs
  runtime/src/dispatcher.rs
  runtime/src/protocol.rs
  runtime/src/transaction/dispatcher.rs
  runtime/src/types.rs
  tests/runtimes/simple-keyvalue/src/main.rs
Labels: c:runtime/compute, c:runtime/scheduler
