Repository oasisprotocol/oasis-core, pull requests merged in 2022-03, with the labels that each got.

#4534 go/worker/common: Don't crash if current descriptor is not ready
  .changelog/4534.bugfix.md
  go/worker/common/committee/node.go
Labels: c:bug

#4538 go/runtime/host/multi: Release lock before calling into runtime
  .changelog/4538.bugfix.md
  go/runtime/host/multi/multi.go
Labels: c:bug

#4541 go/worker/common: Watch for all deployment updates when suspended
  .changelog/4541.bugfix.md
  go/worker/common/committee/node.go
Labels: c:bug

#4542 go/runtime/bundle: Verify SGX signature if present
  .changelog/4542.internal.md
  go/runtime/bundle/bundle.go
Labels: c:common

#4543 go/worker/common: Properly refresh liveness statistics
  .changelog/4543.bugfix.md
  go/worker/common/committee/node.go
Labels: c:bug

#4547 go/logging: libp2p log adapter
  .buildkite/code.pipeline.yml
  .buildkite/longtests.pipeline.yml
  .changelog/4531.internal.md
  go/common/logging/logging.go
  go/common/logging/zap.go
  go/common/logging/zap_test.go
  go/go.mod
  go/go.sum
Labels: s:ready-ci

#4562 go: Bump libp2p to 0.18.0-rc5
  .changelog/4562.internal.md
  go/go.mod
  go/go.sum
Labels: c:deps

#4569 [BACKPORT/22.0.x] Multiple backports
  .buildkite/code.pipeline.yml
  .buildkite/longtests.pipeline.yml
  .changelog/4531.internal.md
  .changelog/4546.feature.md
  .changelog/4548.bugfix.md
  .changelog/4551.bugfix.md
  .changelog/4556.bugfix.md
  .changelog/4557.bugfix.md
  .changelog/4561.cfg.md
  .changelog/4561.feature.md
  .changelog/4562.internal.md
  .changelog/4563.bugfix.md
  .changelog/4564.bugfix.md
  .changelog/4565.internal.md
  .changelog/4568.internal.md
  go/common/logging/logging.go
  go/common/logging/zap.go
  go/common/logging/zap_test.go
  go/common/random/random.go
  go/consensus/tendermint/abci/prune.go
  go/consensus/tendermint/abci/prune_test.go
  go/consensus/tendermint/abci/state.go
  go/consensus/tendermint/full/full.go
  go/consensus/tendermint/full/helpers.go
  go/genesis/genesis_test.go
  go/go.mod
  go/go.sum
  go/oasis-net-runner/fixtures/default.go
  go/oasis-node/cmd/debug/bundle/bundle.go
  go/oasis-node/cmd/ias/auth_registry.go
  go/oasis-node/cmd/ias/proxy.go
  go/oasis-node/cmd/node/node.go
  go/oasis-node/node_test.go
  go/oasis-test-runner/oasis/args.go
  go/oasis-test-runner/oasis/compute.go
  go/registry/api/api.go
  go/registry/api/api_test.go
  go/registry/api/sanity_check.go
  go/runtime/registry/registry.go
  go/runtime/txpool/txpool.go
  go/storage/mkvs/checkpoint/checkpointer.go
  go/storage/mkvs/db/api/api.go
  go/storage/mkvs/db/badger/badger.go
  go/storage/mkvs/tree_test.go
  go/worker/client/service.go
  go/worker/common/committee/p2p.go
  go/worker/compute/executor/committee/p2p.go
  go/worker/compute/executor/tests/tester.go
  go/worker/storage/committee/node.go
  go/worker/storage/init.go
  go/worker/storage/worker.go
  runtime/src/dispatcher.rs
Labels: c:backport

#4575 [BACKPORT/22.0.x] go/worker/registration: Add a random re-registration delay
  .changelog/4574.feature.md
  go/worker/registration/worker.go
Labels: c:backport

#4585 go/registry: Fix invalid sanity check
  .changelog/4585.bugfix.md
  go/consensus/tendermint/apps/registry/transactions_test.go
  go/registry/api/api.go
Labels: c:bug

#4586 [BACKPORT/22.0.x] go/registry: Fix invalid sanity check
  .changelog/4585.bugfix.md
  go/consensus/tendermint/apps/registry/transactions_test.go
  go/registry/api/api.go
Labels: c:backport

#4588 go/oasis-node/cmd: unsafe-reset preserve mkvs by default
  .changelog/4588.feature.md
  go/oasis-node/cmd/node/unsafe_reset.go
  go/oasis-test-runner/oasis/cli/cli.go
Labels: c:cli

#4590 stable/21.3.x backport #4588
  .changelog/4588.feature.md
  go/oasis-node/cmd/node/unsafe_reset.go
  go/oasis-test-runner/oasis/cli/cli.go
Labels: c:cli

#4589 stable/22.0.x backport #4588
  .changelog/4588.feature.md
  go/oasis-node/cmd/node/unsafe_reset.go
  go/oasis-test-runner/oasis/cli/cli.go
Labels: c:cli

#4603 go/registry: Fix node stake claim sanity check with suspended runtimes
  .changelog/4603.bugfix.md
  go/consensus/tendermint/apps/supplementarysanity/checks.go
  go/genesis/genesis_test.go
  go/registry/api/sanity_check.go
Labels: c:bug

#4604 [BACKPORT/22.0.x] go/registry: Fix node stake claim sanity check with suspended runtimes
  .changelog/4603.bugfix.md
  go/consensus/tendermint/apps/supplementarysanity/checks.go
  go/genesis/genesis_test.go
  go/registry/api/sanity_check.go
Labels: c:backport

#4416 go/oasis-node/cmd/stake: Allow querying historical account info
  .changelog/4416.feature.md
  go/oasis-node/cmd/stake/account.go
  go/oasis-node/cmd/stake/stake.go
Labels: c:staking, c:cli

#4417 [BACKPORT/21.3.x] go/oasis-node/cmd/stake: Allow querying historical account info
  .changelog/4416.feature.md
  go/oasis-node/cmd/stake/account.go
  go/oasis-node/cmd/stake/stake.go
Labels: c:backport

#4611 governance: Allow unregistered nodes in votes
  .changelog/4607.breaking.md
  go/common/version/version.go
  go/consensus/tendermint/apps/governance/transactions.go
  runtime/src/common/version.rs
Labels: c:breaking/consensus, c:governance, c:breaking

#4615 go/consensus/tendermint: Record node liveness successes
  .changelog/4615.breaking.md
  go/consensus/tendermint/apps/roothash/liveness.go
  go/consensus/tendermint/apps/roothash/liveness_test.go
Labels: c:bug, c:breaking/consensus

#4622 [BACKPORT/21.3.x] oasis-node/cmd/stake: Print actual latest height when querying info
  .changelog/4622.bugfix.md
  go/oasis-node/cmd/stake/account.go
Labels: c:backport

#4617 go/oasis-node/cmd: Allow using non local gRPC connections
  .changelog/4617.feature.md
  go/oasis-node/cmd/common/grpc/grpc.go
Labels: c:cli
