Repository oasisprotocol/oasis-core, pull requests merged in 2023-01, with the labels that each got.

#5123 go/worker/client: Better handle latest round queries with verification
  .changelog/5123.bugfix.md
  go/runtime/host/protocol/errors.go
  go/worker/client/committee/node.go
Labels: c:bug

#5124 [BACKPORT/22.2.x] go/worker/client: Better handle latest round queries with verification
  .changelog/5120.internal.md
  .changelog/5123.bugfix.md
  Cargo.lock
  go/runtime/host/protocol/errors.go
  go/worker/client/committee/node.go
  keymanager/Cargo.toml
  runtime/Cargo.toml
  tests/runtimes/simple-keyvalue/Cargo.toml
Labels: c:backport

#5136 [BACKPORT/22.2.x] runtime/src/protocol: Remove consensus version compatibility check
  .changelog/5135.internal.md
  runtime/src/common/version.rs
  runtime/src/lib.rs
  runtime/src/protocol.rs
Labels: c:backport

#5125 go/common/node: Add runtime encryption key (REK)
  .changelog/5125.feature.md
  go/common/node/node.go
  go/common/node/node_test.go
  go/common/node/sgx.go
  go/common/node/sgx_test.go
  go/consensus/tendermint/apps/registry/state/interop/interop.go
  go/consensus/tendermint/apps/scheduler/scheduler.go
  go/oasis-node/cmd/debug/byzantine/steps.go
  go/roothash/api/commitment/txnscheduler.go
  go/runtime/host/protocol/types.go
  go/runtime/host/sgx/sgx.go
  runtime/src/attestation.rs
  runtime/src/consensus/registry.rs
  runtime/src/consensus/state/registry.rs
  runtime/src/dispatcher.rs
  runtime/src/enclave_rpc/session.rs
  runtime/src/protocol.rs
  runtime/src/rak.rs
  runtime/src/types.rs
Labels: c:registry, c:keymgmt, golang, rust

#5151 [BACKPORT/22.2.x] Multiple verifier-related backports
  .buildkite/pipeline.sh
  .changelog/5146.internal.md
  .changelog/5148.bugfix.md
  .changelog/5149.internal.md
  Cargo.lock
  runtime/Cargo.toml
  runtime/src/common/mod.rs
  runtime/src/common/process.rs
  runtime/src/common/sgx/mod.rs
  runtime/src/common/sgx/pcs.rs
  runtime/src/consensus/tendermint/verifier/mod.rs
  runtime/src/consensus/tendermint/verifier/store/lru.rs
  runtime/src/dispatcher.rs
Labels: c:backport

#5155 Fix build documentation typo
  .changelog/5155.trivial.md
  Makefile
Labels: p:3, c:build

#5156 runtime/src/enclave_rpc: Support calls to explicit key manager members
  .changelog/5156.feature.md
  go/p2p/rpc/peermgmt.go
  go/runtime/host/protocol/types.go
  go/runtime/keymanager/api/api.go
  go/runtime/registry/host.go
  go/worker/common/committee/keymanager.go
  go/worker/keymanager/p2p/client.go
  go/worker/storage/p2p/sync/client.go
  keymanager/src/client/remote.rs
  keymanager/src/crypto/kdf.rs
  runtime/src/enclave_rpc/client.rs
  runtime/src/enclave_rpc/session.rs
  runtime/src/enclave_rpc/transport.rs
  runtime/src/types.rs
  tests/runtimes/simple-keyvalue/src/main.rs
Labels: golang, rust
