Repository oasisprotocol/oasis-core, pull requests merged in 2023-11, with the labels that each got.

#5423 go/consensus: Do not crash on nil result from Commit
  .changelog/5423.bugfix.md
  go/consensus/cometbft/full/common.go
Labels: c:bug

#5424 [BACKPORT/23.0.x] Multiple backports
  .changelog/5421.internal.md
  .changelog/5422.trivial.md
  .changelog/5423.bugfix.md
  .github/workflows/ci-lint.yml
  go/consensus/cometbft/full/common.go
  go/go.mod
  go/go.sum
  go/worker/keymanager/worker.go
Labels: c:backport

#5431 [BACKPORT/23.0.x] 5426
  .changelog/5426.bugfix.md
  go/consensus/cometbft/apps/roothash/finalization.go
  go/consensus/cometbft/apps/roothash/roothash.go
  go/consensus/cometbft/apps/roothash/timeout.go
  go/consensus/cometbft/apps/roothash/transactions.go
  go/roothash/api/api.go
  go/roothash/tests/tester.go
  go/runtime/host/sgx/sgx.go
  go/runtime/txpool/txpool.go
  go/worker/client/committee/node.go
  go/worker/common/committee/group.go
  go/worker/common/committee/node.go
  go/worker/common/committee/p2p.go
  go/worker/compute/executor/committee/discrepancy.go
  go/worker/compute/executor/committee/hooks.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/p2p.go
  go/worker/storage/committee/node.go
Labels: c:bug, c:backport

#5434 [BACKPORT/23.0.x] go/runtime/host/multi: Propagate consensus sync requests to next version
  .changelog/5433.bugfix.md
  go/runtime/host/multi/multi.go
Labels: c:backport

#5438 go/runtime/host/sandbox: Release lock before calling into runtime
  .changelog/5438.bugfix.2.md
  .changelog/5438.bugfix.md
  go/runtime/host/sandbox/sandbox.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/state.go
  runtime/Cargo.toml
  runtime/src/dispatcher.rs
  runtime/src/protocol.rs
Labels: c:bug

#5439 [BACKPORT/23.0.x] Multiple backports
  .changelog/5430.trivial.md
  .changelog/5436.feature.md
  .changelog/5438.bugfix.2.md
  .changelog/5438.bugfix.md
  go/consensus/cometbft/api/api.go
  go/consensus/cometbft/apps/roothash/roothash.go
  go/consensus/cometbft/apps/roothash/transactions.go
  go/consensus/cometbft/roothash/roothash.go
  go/oasis-node/cmd/common/grpc/grpc.go
  go/roothash/api/api.go
  go/roothash/api/grpc.go
  go/runtime/host/multi/multi.go
  go/runtime/host/sandbox/sandbox.go
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/state.go
  runtime/Cargo.toml
  runtime/src/dispatcher.rs
  runtime/src/protocol.rs
Labels: c:backport

#5443 [BACKPORT/23.0.x] 5442
  .changelog/5442.bugfix.md
  go/runtime/host/protocol/connection.go
  go/runtime/host/sgx/sgx.go
Labels: c:backport

#5450 runtime: Create controller in RpcClient constructor
  .changelog/5450.bugfix.md
  runtime/src/dispatcher.rs
  runtime/src/enclave_rpc/client.rs
Labels: c:bug

#5454 [BACKPORT/23.0.x] Multiple backports
  .changelog/5446.bugfix.2.md
  .changelog/5446.bugfix.md
  .changelog/5447.bugfix.2.md
  .changelog/5447.bugfix.md
  .changelog/5448.bugfix.md
  .changelog/5450.bugfix.md
  .changelog/5453.bugfix.md
  .changelog/5456.bugfix.2.md
  .changelog/5456.bugfix.md
  go/consensus/cometbft/apps/roothash/transactions.go
  go/p2p/discovery/bootstrap/client.go
  go/p2p/host.go
  go/p2p/rpc/client.go
  go/p2p/rpc/nop.go
  go/runtime/host/host.go
  go/runtime/host/mock/mock.go
  go/runtime/host/multi/multi.go
  go/runtime/host/sandbox/sandbox.go
  go/runtime/registry/host.go
  go/runtime/txpool/txpool.go
  go/worker/compute/executor/committee/node.go
  go/worker/registration/worker.go
  runtime/src/dispatcher.rs
  runtime/src/enclave_rpc/client.rs
Labels: c:backport

#5463 [BACKPORT/23.0.x] go/consensus/cometbft/light: Don't crash when signed header unavailable
  .changelog/5462.bugfix.md
  go/consensus/cometbft/light/service.go
Labels: c:backport

#5468 [BACKPORT/23.0.x] go/consensus/cometbft/light: Try multiple sources when fetching blocks
  .changelog/5466.bugfix.md
  .changelog/5466.cfg.md
  go/consensus/api/light.go
  go/consensus/cometbft/abci/prune.go
  go/consensus/cometbft/cometbft.go
  go/consensus/cometbft/config/config.go
  go/consensus/cometbft/full/full.go
  go/consensus/cometbft/light/api/light.go
  go/consensus/cometbft/light/internal.go
  go/consensus/cometbft/light/p2p/p2p.go
  go/consensus/cometbft/light/service.go
  go/consensus/p2p/light/server.go
  go/oasis-node/cmd/node/node.go
Labels: c:backport

#5469 go/p2p/peermgmt/backup: Prevent overwriting TTL when restoring peers
  .changelog/5469.bugfix.md
  go/p2p/peermgmt/backup.go
Labels: c:bug

#5474 [BACKPORT/23.0.x] go/oasis-node: Remove obsolete db section during config migration
  .changelog/5473.bugfix.md
  go/oasis-node/cmd/config/migrate/migrate.go
  go/oasis-node/cmd/config/migrate/migrate_test.go
Labels: c:backport

#5477 [BACKPORT/23.0.x] go/p2p/discovery: Close only idle connections to seed node
  .changelog/5476.bugfix.md
  go/p2p/discovery/bootstrap/client.go
  go/p2p/rpc/client.go
  go/p2p/rpc/nop.go
Labels: c:backport

#5482 [BACKPORT/23.0.x] go/consensus/cometbft/light: Only fetch from light store for now
  .changelog/5481.bugfix.md
  go/consensus/cometbft/light/service.go
  go/oasis-test-runner/scenario/e2e/genesis_file.go
Labels: c:backport

#5483 [BACKPORT/23.0.x] Multiple backports
  .cargo/audit.toml
  .changelog/5480.bugfix.md
  .changelog/5484.trivial.md
  go/p2p/peermgmt/peermgr.go
Labels: c:backport
