Repository oasisprotocol/oasis-core, pull requests merged in 2023-03, with the labels that each got.

#5213 rust: Bump tempfile to 3.4.0
  .changelog/5213.internal.md
  Cargo.lock
  runtime/Cargo.toml
Labels: c:deps

#5215 keymanager: Support policies in unsafe builds
  .changelog/5215.internal.md
  go/oasis-node/cmd/keymanager/keymanager.go
  go/oasis-test-runner/oasis/fixture.go
  go/oasis-test-runner/oasis/keymanager.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime.go
  go/worker/keymanager/watcher.go
  go/worker/keymanager/worker.go
  keymanager/src/client/remote.rs
  keymanager/src/policy/cached.rs
Labels: c:testing

#5218 go/worker/keymanager: Optimize enclave initialization
  .changelog/5218.internal.md
  go/worker/keymanager/init.go
  go/worker/keymanager/status.go
  go/worker/keymanager/worker.go
Labels: golang

#5230 [BACKPORT/22.2.x] docker: Switch to ghcr.io for container registry
  .buildkite/benchmarks.pipeline.yml
  .buildkite/code.pipeline.yml
  .buildkite/longtests.pipeline.yml
  .buildkite/pipeline.sh
  .changelog/5224.internal.md
  .github/workflows/docker.yml
  Cargo.lock
  Makefile
  docker/Makefile
  docker/oasis-core-ci/Dockerfile
  docs/development-setup/building.md
  docs/development-setup/prerequisites.md
Labels: c:backport
