Repository oasisprotocol/oasis-core, pull requests merged in 2023-07, with the labels that each got.

#5307 go/oasis-test-runner: Build key manager runtime with trust root
  .changelog/5307.internal.md
  go/oasis-test-runner/rust/builder.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_client_kv.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_client_kv_scenario.go
  go/oasis-test-runner/scenario/e2e/runtime/trust_root.go
  go/oasis-test-runner/scenario/e2e/runtime/trust_root_change.go
  runtime/src/consensus/tendermint/verifier/noop.rs
  runtime/src/protocol.rs
  tests/runtimes/simple-keymanager/src/main.rs
Labels: c:testing, golang, rust

#5308 [BACKPORT/22.2.x] go/oasis-test-runner: Build key manager runtime with trust root
  .changelog/5308.internal.md
  go/oasis-test-runner/cmd/root.go
  go/oasis-test-runner/rust/builder.go
  go/oasis-test-runner/scenario/e2e/byzantine_beacon_vrf.go
  go/oasis-test-runner/scenario/e2e/consensus_state_sync.go
  go/oasis-test-runner/scenario/e2e/debond.go
  go/oasis-test-runner/scenario/e2e/early_query.go
  go/oasis-test-runner/scenario/e2e/gas_fees_staking.go
  go/oasis-test-runner/scenario/e2e/genesis_file.go
  go/oasis-test-runner/scenario/e2e/identity_cli.go
  go/oasis-test-runner/scenario/e2e/min_transact_balance.go
  go/oasis-test-runner/scenario/e2e/multiple_seeds.go
  go/oasis-test-runner/scenario/e2e/registry_cli.go
  go/oasis-test-runner/scenario/e2e/runtime/archive_api.go
  go/oasis-test-runner/scenario/e2e/runtime/byzantine.go
  go/oasis-test-runner/scenario/e2e/runtime/dump_restore.go
  go/oasis-test-runner/scenario/e2e/runtime/gas_fees.go
  go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go
  go/oasis-test-runner/scenario/e2e/runtime/halt_restore.go
  go/oasis-test-runner/scenario/e2e/runtime/halt_restore_nonmock.go
  go/oasis-test-runner/scenario/e2e/runtime/history_reindex.go
  go/oasis-test-runner/scenario/e2e/runtime/keymanager_key_generation.go
  go/oasis-test-runner/scenario/e2e/runtime/keymanager_replicate.go
  go/oasis-test-runner/scenario/e2e/runtime/keymanager_restart.go
  go/oasis-test-runner/scenario/e2e/runtime/keymanager_upgrade.go
  go/oasis-test-runner/scenario/e2e/runtime/late_start.go
  go/oasis-test-runner/scenario/e2e/runtime/multiple_runtimes.go
  go/oasis-test-runner/scenario/e2e/runtime/node_shutdown.go
  go/oasis-test-runner/scenario/e2e/runtime/offset_restart.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_client_kv.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_client_kv_scenario.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_dynamic.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_governance.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_message.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_prune.go
  go/oasis-test-runner/scenario/e2e/runtime/runtime_upgrade.go
  go/oasis-test-runner/scenario/e2e/runtime/sentry.go
  go/oasis-test-runner/scenario/e2e/runtime/storage_early_state_sync.go
  go/oasis-test-runner/scenario/e2e/runtime/storage_sync.go
  go/oasis-test-runner/scenario/e2e/runtime/storage_sync_from_registered.go
  go/oasis-test-runner/scenario/e2e/runtime/storage_sync_inconsistent.go
  go/oasis-test-runner/scenario/e2e/runtime/trust_root.go
  go/oasis-test-runner/scenario/e2e/runtime/trust_root_change.go
  go/oasis-test-runner/scenario/e2e/runtime/txsource.go
  go/oasis-test-runner/scenario/e2e/seed_api.go
  go/oasis-test-runner/scenario/e2e/stake_cli.go
  go/oasis-test-runner/scenario/e2e/upgrade.go
  go/oasis-test-runner/scenario/e2e/upgrade_cancel.go
  go/oasis-test-runner/scenario/e2e/validator_equivocation.go
  go/oasis-test-runner/scenario/pluginsigner/basic.go
  go/oasis-test-runner/scenario/remotesigner/basic.go
  go/oasis-test-runner/scenario/scenario.go
  runtime/src/consensus/tendermint/verifier/noop.rs
  runtime/src/protocol.rs
  tests/runtimes/simple-keymanager/src/main.rs
Labels: c:testing, c:backport

#5314 [BACKPORT/22.2.x] Fix Discord links again to use URL under our control
  .changelog/5313.trivial.md
  CONTRIBUTING.md
  GOVERNANCE.md
Labels: c:backport

#5322 [BACKPORT/22.2.x] go/storage/mkvs: Fix commit of nil entries
  .changelog/5321.bugfix.md
  go/storage/mkvs/commit.go
  go/storage/mkvs/tree_test.go
Labels: c:backport
