Repository oasisprotocol/oasis-core, pull requests merged in 2023-08, with the labels that each got.

#5334 go/consensus/roothash: Track runtime proposer liveness
  .changelog/5334.breaking.md
  go/consensus/cometbft/apps/roothash/liveness.go
  go/consensus/cometbft/apps/roothash/liveness_test.go
  go/consensus/cometbft/apps/roothash/roothash.go
  go/consensus/cometbft/apps/roothash/transactions.go
  go/registry/api/runtime.go
  go/registry/api/runtime_test.go
  go/roothash/api/liveness.go
  go/roothash/tests/tester.go
  go/scheduler/api/api.go
  runtime/src/consensus/registry.rs
Labels: golang, rust, c:breaking

#5338 go: Bump go-libp2p to 0.29.1
  .changelog/5338.internal.md
  go/go.mod
  go/go.sum
Labels: golang, c:deps

#5336 [BACKPORT/22.2.x] go/common/cbor: Relax CBOR decoding for gRPC/RHP endpoints
  .changelog/5335.bugfix.md
  .changelog/5337.internal.md
  .changelog/5338.internal.md
  go/common/cbor/cbor.go
  go/common/cbor/cbor_test.go
  go/common/cbor/codec.go
  go/common/grpc/cbor.go
  go/go.mod
  go/go.sum
Labels: c:backport

#5347 [22.2.x] Pin tendermint links to 22.2.x branch
  .changelog/5347.doc.md
  docs/consensus/README.md
Labels: c:docs

#5355 go: Bump go-libp2p to 0.30.0
  .changelog/5355.internal.md
  go/go.mod
  go/go.sum
Labels: golang, c:deps
