Repository oasisprotocol/oasis-core, pull requests merged in 2023-02, with the labels that each got.

#5161 go/worker/compute: Do not drop valid proposals
  .changelog/5161.bugfix.md
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/p2p.go
  go/worker/compute/executor/committee/proposals.go
  go/worker/compute/executor/committee/state.go
Labels: c:bug

#5166 go/keymanager/api: Move key manager gas costs
  .changelog/5166.breaking.md
  go/consensus/tendermint/apps/keymanager/genesis.go
  go/consensus/tendermint/apps/keymanager/messages.go
  go/consensus/tendermint/apps/keymanager/messages_test.go
  go/consensus/tendermint/apps/keymanager/state/state.go
  go/consensus/tendermint/apps/keymanager/transactions.go
  go/genesis/genesis_test.go
  go/keymanager/api/api.go
  go/keymanager/api/sanity_check.go
  go/oasis-node/cmd/debug/fixgenesis/fixgenesis.go
  go/oasis-node/cmd/genesis/genesis.go
  go/registry/api/api.go
Labels: golang, c:breaking/consensus

#5162 [BACKPORT/22.2.x] go/worker/compute: Do not drop valid proposals
  .changelog/5161.bugfix.md
  go/worker/compute/executor/committee/node.go
  go/worker/compute/executor/committee/p2p.go
  go/worker/compute/executor/committee/proposals.go
  go/worker/compute/executor/committee/state.go
Labels: c:backport

#5177 go/registry/api: Fix node registration when TEE not available
  .changelog/5177.bugfix.md
  go/registry/api/api.go
  go/registry/tests/tester.go
Labels: c:registry, c:breaking/consensus

#5182 docs: Fix development setup instructions
  .changelog/5182.trivial.md
  docs/development-setup/prerequisites.md
Labels: c:docs

#5195 go: Bump go-libp2p-pubsub to 0.9.1
  .changelog/5195.internal.md
  go/go.mod
  go/go.sum
Labels: c:deps

#5203 [BACKPORT/22.2.x] Move halt epoch from genesis to node-local configuration
  .changelog/5200.feature.md
  go/consensus/tendermint/abci/mux.go
  go/consensus/tendermint/abci/state.go
  go/consensus/tendermint/full/archive.go
  go/consensus/tendermint/full/full.go
  go/oasis-test-runner/oasis/network.go
  go/oasis-test-runner/scenario/e2e/e2e.go
  go/oasis-test-runner/scenario/e2e/runtime/halt_restore.go
  go/oasis-test-runner/scenario/e2e/runtime/halt_restore_nonmock.go
Labels: c:backport
