Repository oasisprotocol/oasis-core, pull requests merged in 2024-10, with the labels that each got.

#5856 go: Bump github.com/dgraph-io/badger to v4.3.1
  .changelog/5856.internal.md
  go/go.mod
  go/go.sum
Labels: c:deps

#5897 secret-sharing/src/churp/switch: Verify combined bivariate polynomial
  .changelog/5897.internal.md
  keymanager/src/churp/handler.rs
  secret-sharing/src/churp/dealer.rs
  secret-sharing/src/churp/errors.rs
  secret-sharing/src/churp/handoff.rs
  secret-sharing/src/churp/player.rs
  secret-sharing/src/churp/shareholder.rs
  secret-sharing/src/churp/switch.rs
  secret-sharing/src/vss/matrix.rs
Labels: c:key management

#5912 [BACKPORT/24.3.x] runtime: Do not persist updated trusted state for TDX
  .changelog/5909.bugfix.md
  runtime/src/consensus/tendermint/verifier/store/state.rs
Labels: c:backport

#5917 runtime/src/enclave_rpc/client: Fix panic on drop in async context
  .changelog/5917.bugfix.md
  runtime/src/enclave_rpc/client.rs
Labels: c:bug
